import test from 'node:test';
import assert from 'node:assert/strict';
import { ALL_FUSION_JOBS, FUSION_VALIDATION, getFusionJob, generatedFusionId } from '../js/data/jobFusion.js';
import { fusionConstellationFor } from '../js/data/fusionConstellation.js';

test('Phase 8 registry contains exactly 105 unique pairs',()=>{assert.equal(ALL_FUSION_JOBS.length,105);assert.equal(FUSION_VALIDATION.ok,true,FUSION_VALIDATION.errors.join('\n'));assert.deepEqual(FUSION_VALIDATION.counts,{total:105,ids:105,pairs:105,names:105,legacy:30,fusion:75});});
test('legacy ids survive while display names can evolve',()=>{assert.equal(getFusionJob('warrior','fighter').id,'battlemaster');assert.equal(getFusionJob('fighter','warrior').name,'羅刹');assert.equal(getFusionJob('thief','merchant').id,'treasurehunter');});
test('new pair ids are deterministic and order independent',()=>{assert.equal(generatedFusionId('warrior','merchant'),'fusion_warrior_merchant');assert.equal(generatedFusionId('merchant','warrior'),'fusion_warrior_merchant');assert.equal(getFusionJob('thief','scholar').name,'遺物探究家');assert.equal(getFusionJob('priest','dancer').name,'神楽巫女');});
test('every fusion job has identity, resource, constellation and loot metadata',()=>{for(const job of ALL_FUSION_JOBS){assert.ok(job.fusionTrait?.id,job.id);assert.ok(job.resourceInteraction?.id,job.id);assert.ok(job.constellation?.ultimate,job.id);assert.ok(job.lootTags.length>=4,job.id);}});
test('every fusion constellation has two exclusive paths converging on one Ultimate',()=>{for(const job of ALL_FUSION_JOBS){const t=fusionConstellationFor(job.id);assert.equal(t.length,6,job.id);const paths=t.filter(n=>n.kind==='fusionSpecialization'),keys=t.filter(n=>n.kind==='fusionKeystone'),ult=t.find(n=>n.kind==='fusionUltimate');assert.equal(paths.length,2,job.id);assert.equal(keys.length,2,job.id);assert.equal(paths[0].exclusiveGroup,paths[1].exclusiveGroup,job.id);assert.equal(ult.requiresAny.length,2,job.id);assert.ok(keys.every(k=>ult.requiresAny.includes(k.id)),job.id);assert.ok(t.some(n=>n.id===`${job.id}_trait`));assert.ok(t.some(n=>n.id===`${job.id}_keystone`));assert.ok(t.some(n=>n.id===`${job.id}_ultimate`));}});
