import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { RANCH3_CAPABILITIES,ranch3AiLabel,ranch3CapabilityState,ranch3TrainingLabel } from '../js/data/settlementRanch3.js';

test('Settlement S8 exposes canonical Ranch capabilities without inventing progression',()=>{assert.deepEqual(RANCH3_CAPABILITIES.map(x=>x.id),['roster','training','traitAnalysis','breeding','directedInheritance','mutation','natureAi']);assert.equal(ranch3AiLabel('aggressive'),'攻勢');assert.equal(ranch3AiLabel('defensive'),'防衛');assert.equal(ranch3AiLabel('support'),'支援');assert.equal(ranch3AiLabel('balanced'),'均衡');assert.equal(ranch3TrainingLabel('power'),'力');});

test('Settlement S8 capability gates follow existing ranch facilities and research unlocks',()=>{let s=ranch3CapabilityState({ranchLevel:1,facilityLevels:{},researchUnlocks:{}});assert.equal(s.roster,true);assert.equal(s.natureAi,true);assert.equal(s.training,false);assert.equal(s.breeding,false);assert.equal(s.directedInheritance,false);assert.equal(s.mutation,false);s=ranch3CapabilityState({ranchLevel:10,facilityLevels:{incubator:1,training:1,mutationLab:1},researchUnlocks:{traitAnalysis:true,directedInheritance:true,mutationHints:true}});assert.equal(s.training,true);assert.equal(s.traitAnalysis,true);assert.equal(s.breeding,true);assert.equal(s.directedInheritance,true);assert.equal(s.mutation,true);});

test('Settlement S8 runtime delegates to existing Monster Ranch and Nature AI state',()=>{const runtime=fs.readFileSync(new URL('../js/patches/settlementRanch3.js',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../js/patches/settlementRanch3Ui.js',import.meta.url),'utf8'),nav=fs.readFileSync(new URL('../js/patches/homeNavigation.js',import.meta.url),'utf8');assert.match(runtime,/ranchCompanionInfo/);assert.match(runtime,/ranchResearchArchive/);assert.match(runtime,/ranchResearchUnlocks/);assert.match(runtime,/ranchFacilityLevel/);assert.match(runtime,/ranchCapacity/);assert.match(runtime,/COMPANION_NATURES/);assert.doesNotMatch(runtime,/state\.data\.ranch3|__settlement3\.ranch3|ranch3Currency/);assert.doesNotMatch(runtime,/createBreedingEgg\s*=|createDirectedBreedingEgg\s*=|rollRanchMutation\s*=|awakenRanchMutation\s*=/);assert.doesNotMatch(runtime,/setInterval|setTimeout|Date\.now|daily/i);assert.match(ui,/data-settlement-ranch3/);assert.match(ui,/data-ranch3-individual/);assert.match(ui,/goCompanionBtn/);assert.match(ui,/<details/);assert.match(ui,/Companion AI/);assert.doesNotMatch(ui,/setInterval|setTimeout|Date\.now|daily/i);assert.match(nav,/settlementRanch3\.js/);assert.match(nav,/settlementRanch3Ui\.js/);assert.doesNotMatch(nav,/goRanch3Btn/);});

test('Settlement S8 keeps breeding and mutation authoritative in existing modules',()=>{const breeding=fs.readFileSync(new URL('../js/patches/monsterRanch2Facilities.js',import.meta.url),'utf8'),complete=fs.readFileSync(new URL('../js/patches/monsterRanch2Complete.js',import.meta.url),'utf8'),mutations=fs.readFileSync(new URL('../js/patches/monsterRanchMutations.js',import.meta.url),'utf8'),battle=fs.readFileSync(new URL('../js/patches/companionBattle.js',import.meta.url),'utf8');assert.match(breeding,/createBreedingEgg/);assert.match(complete,/createDirectedBreedingEgg/);assert.match(mutations,/rollRanchMutation/);assert.match(mutations,/awakenRanchMutation/);assert.match(battle,/COMPANION_NATURES/);assert.match(battle,/nature\.ai|\.ai===/);});
