import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { SETTLEMENT_BUILDINGS,SETTLEMENT_MAX_LEVEL,settlementCost,settlementEffectiveLevels,settlementEraForLevel,settlementMaterialYield } from '../js/data/settlement.js';

test('Settlement 3.0 keeps five core facilities but extends them to level 20',()=>{assert.equal(SETTLEMENT_BUILDINGS.length,5);assert.equal(new Set(SETTLEMENT_BUILDINGS.map(x=>x.id)).size,5);assert.ok(SETTLEMENT_BUILDINGS.some(x=>x.id==='ranch'));assert.equal(SETTLEMENT_MAX_LEVEL,20);assert.ok(SETTLEMENT_BUILDINGS.every(x=>x.maxLevel===20&&x.costs.length===20));});
test('legacy levels 1-5 keep their original cost curve before long-term progression continues',()=>{assert.deepEqual(settlementCost('hall',1),{wood:20,ore:10,hide:0,veilstone:0});assert.deepEqual(settlementCost('hall',5),{wood:210,ore:105,hide:0,veilstone:0});for(const b of SETTLEMENT_BUILDINGS){const l5=settlementCost(b.id,5),l10=settlementCost(b.id,10),l20=settlementCost(b.id,20);const total=c=>Object.values(c).reduce((n,v)=>n+v,0);assert.ok(l5&&l10&&l20);assert.ok(total(l10)>total(l5));assert.ok(total(l20)>total(l10));}});
test('post-level-5 effects taper instead of scaling linearly to a broken level-20 bonus',()=>{assert.equal(settlementEffectiveLevels(0),0);assert.equal(settlementEffectiveLevels(5),5);assert.equal(settlementEffectiveLevels(10),7.5);assert.equal(settlementEffectiveLevels(15),8.75);assert.equal(settlementEffectiveLevels(20),9.375);});
test('settlement eras change at the four major hall milestones',()=>{assert.equal(settlementEraForLevel(0).name,'開拓地');assert.equal(settlementEraForLevel(5).name,'開拓村');assert.equal(settlementEraForLevel(10).name,'交易町');assert.equal(settlementEraForLevel(15).name,'城塞都市');assert.equal(settlementEraForLevel(20).name,'辺境首都');});
test('story and Abyss clears feed different settlement materials',()=>{const story=settlementMaterialYield({recLevel:100,boss:false}),abyss=settlementMaterialYield({isAbyss:true,abyssDepth:500,boss:true});assert.ok(story.wood>0);assert.equal(story.veilstone,0);assert.ok(abyss.veilstone>0);assert.ok(abyss.ore>story.ore);});
test('Settlement hooks into hub, tapered effects, Ranch recruitment, and visible era UI',()=>{const nav=fs.readFileSync(new URL('../js/patches/homeNavigation.js',import.meta.url),'utf8'),rec=fs.readFileSync(new URL('../js/patches/companionRecruitment.js',import.meta.url),'utf8'),core=fs.readFileSync(new URL('../js/patches/settlementCore.js',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../js/patches/settlementUi.js',import.meta.url),'utf8');assert.match(nav,/goSettlementBtn/);assert.match(nav,/settlementCore/);assert.match(rec,/recruitChanceBonus/);assert.match(core,/gainPartyCompanionExp/);assert.match(core,/settlementEffectiveLevels/);assert.match(core,/settlementMaterials/);assert.match(ui,/settlementEraForLevel/);assert.match(ui,/Lv\.5 \/ 10 \/ 15 \/ 20/);});
