import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { SETTLEMENT_AREA_GROUPS,SETTLEMENT_BUILDINGS,SETTLEMENT_ERAS,SETTLEMENT_MAX_LEVEL,SETTLEMENT_RESIDENTS,SETTLEMENT_RESIDENT_ROLES,settlementCost,settlementEffectiveLevels,settlementEraAtMilestone,settlementEraForLevel,settlementMaterialYield,settlementReachedEras,settlementResidentEligible,settlementResidentRole } from '../js/data/settlement.js';
import { TAVERN_REQUESTS,TAVERN_UNLOCK_HALL_LEVEL,buildTavernRumors,tavernRequestComplete } from '../js/data/settlementTavern.js';
import { PRODUCTION_FACILITIES,PRODUCTION_GOODS,PRODUCTION_RECIPES,PRODUCTION_UNLOCK_HALL_LEVEL,productionCanCraft,productionFacilityUnlocked,productionRecipeUnlocked } from '../js/data/settlementProduction.js';

test('Settlement 3.0 keeps five core facilities but extends them to level 20',()=>{assert.equal(SETTLEMENT_BUILDINGS.length,5);assert.equal(new Set(SETTLEMENT_BUILDINGS.map(x=>x.id)).size,5);assert.ok(SETTLEMENT_BUILDINGS.some(x=>x.id==='ranch'));assert.equal(SETTLEMENT_MAX_LEVEL,20);assert.ok(SETTLEMENT_BUILDINGS.every(x=>x.maxLevel===20&&x.costs.length===20));});
test('legacy levels 1-5 keep their original cost curve before long-term progression continues',()=>{assert.deepEqual(settlementCost('hall',1),{wood:20,ore:10,hide:0,veilstone:0});assert.deepEqual(settlementCost('hall',5),{wood:210,ore:105,hide:0,veilstone:0});for(const b of SETTLEMENT_BUILDINGS){const l5=settlementCost(b.id,5),l10=settlementCost(b.id,10),l20=settlementCost(b.id,20);const total=c=>Object.values(c).reduce((n,v)=>n+v,0);assert.ok(l5&&l10&&l20);assert.ok(total(l10)>total(l5));assert.ok(total(l20)>total(l10));}});
test('post-level-5 effects taper instead of scaling linearly to a broken level-20 bonus',()=>{assert.equal(settlementEffectiveLevels(0),0);assert.equal(settlementEffectiveLevels(5),5);assert.equal(settlementEffectiveLevels(10),7.5);assert.equal(settlementEffectiveLevels(15),8.75);assert.equal(settlementEffectiveLevels(20),9.375);});
test('settlement eras change at the four major hall milestones and expose visual identity',()=>{assert.equal(settlementEraForLevel(0).name,'開拓地');assert.equal(settlementEraForLevel(5).name,'開拓村');assert.equal(settlementEraForLevel(10).name,'交易町');assert.equal(settlementEraForLevel(15).name,'城塞都市');assert.equal(settlementEraForLevel(20).name,'辺境首都');assert.deepEqual([5,10,15,20].map(x=>settlementEraAtMilestone(x)?.id),['village','town','city','capital']);assert.equal(settlementEraAtMilestone(6),null);assert.deepEqual(settlementReachedEras(14).map(x=>x.id),['village','town']);for(const era of SETTLEMENT_ERAS){assert.ok(era.icon&&era.tagline&&era.atmosphere&&era.visualClass);}});
test('Settlement S2 area groups cover each legacy core facility exactly once',()=>{const ids=SETTLEMENT_AREA_GROUPS.flatMap(x=>x.buildingIds);assert.deepEqual([...ids].sort(),SETTLEMENT_BUILDINGS.map(x=>x.id).sort());assert.equal(new Set(ids).size,SETTLEMENT_BUILDINGS.length);assert.deepEqual(SETTLEMENT_AREA_GROUPS.map(x=>x.id),['center','life','trade','defense']);});
test('Settlement S3 residents have identity, role, placement, event, and deterministic unlock contracts',()=>{assert.ok(SETTLEMENT_RESIDENTS.length>=7);assert.equal(new Set(SETTLEMENT_RESIDENTS.map(r=>r.id)).size,SETTLEMENT_RESIDENTS.length);for(const r of SETTLEMENT_RESIDENTS){assert.ok(r.name&&r.role&&r.buildingId&&r.event&&r.source);assert.ok(SETTLEMENT_BUILDINGS.some(b=>b.id===r.buildingId));assert.ok(settlementResidentRole(r.role));}for(const role of ['smith','merchant','apothecary','scholar','adventurer','tamer','traveler'])assert.ok(SETTLEMENT_RESIDENT_ROLES[role]);const base={hall:5,buildings:{hall:5,inn:5,market:5,watch:5,ranch:5},stageClears:0,codexSeen:0,codexKills:0,recruitedCodex:0};assert.equal(settlementResidentEligible(SETTLEMENT_RESIDENTS.find(r=>r.id==='garrick'),base),true);assert.equal(settlementResidentEligible(SETTLEMENT_RESIDENTS.find(r=>r.id==='ruka'),base),false);assert.equal(settlementResidentEligible(SETTLEMENT_RESIDENTS.find(r=>r.id==='ruka'),{...base,stageClears:12}),true);assert.equal(settlementResidentEligible(SETTLEMENT_RESIDENTS.find(r=>r.id==='iris'),{...base,hall:10,codexSeen:10}),true);});
test('Settlement S4 tavern unlocks at village rank and keeps requests deterministic',()=>{assert.equal(TAVERN_UNLOCK_HALL_LEVEL,5);assert.ok(TAVERN_REQUESTS.some(r=>r.type==='normal'));assert.ok(TAVERN_REQUESTS.some(r=>r.type==='long'));assert.equal(new Set(TAVERN_REQUESTS.map(r=>r.id)).size,TAVERN_REQUESTS.length);for(const r of TAVERN_REQUESTS){assert.ok(r.goal?.key&&r.goal?.value>0);assert.ok(r.reward?.gold||Object.keys(r.reward?.materials||{}).length);assert.equal(tavernRequestComplete(r,{[r.goal.key]:r.goal.value}),true);assert.equal(tavernRequestComplete(r,{[r.goal.key]:r.goal.value-1}),false);}});
test('Settlement S4 rumors surface existing-system information without random story gating',()=>{const rumors=buildTavernRumors({hall:10,abyssBestDepth:80,rareSeen:3,activeNemesis:{title:'宿敵'},worldEventText:'世界事件が発生中'});for(const id of ['nemesis','abyss','rare','secret','world_event'])assert.ok(rumors.some(r=>r.id===id));assert.ok(rumors.every(r=>r.title&&r.text&&r.source));assert.ok(buildTavernRumors({hall:5}).some(r=>r.id==='quiet'));});
test('Settlement S5 production district unlocks at town rank and has four non-currency processed goods',()=>{assert.equal(PRODUCTION_UNLOCK_HALL_LEVEL,10);assert.deepEqual(Object.keys(PRODUCTION_GOODS).sort(),['bait','frame','ration','remedy']);assert.deepEqual(PRODUCTION_FACILITIES.map(f=>f.id),['farm','mine','lumber','workshop']);for(const f of PRODUCTION_FACILITIES){assert.ok(f.linkedBuilding&&f.minLinkedLevel>0&&f.desc);}assert.ok(PRODUCTION_RECIPES.some(r=>r.output.good==='ration'));assert.ok(PRODUCTION_RECIPES.some(r=>r.output.good==='remedy'));assert.ok(PRODUCTION_RECIPES.some(r=>r.output.good==='bait'));assert.ok(PRODUCTION_RECIPES.some(r=>r.output.good==='frame'));});
test('Settlement S5 crafting is manual, material-backed, and facility-gated',()=>{const recipe=PRODUCTION_RECIPES.find(r=>r.id==='building_frame'),locked={hall:9,buildings:{market:20},materials:{wood:999,ore:999}},ready={hall:10,buildings:{market:10},materials:{wood:12,ore:5}};assert.equal(productionFacilityUnlocked(PRODUCTION_FACILITIES.find(f=>f.id==='lumber'),locked),false);assert.equal(productionRecipeUnlocked(recipe,locked),false);assert.equal(productionRecipeUnlocked(recipe,ready),true);assert.equal(productionCanCraft(recipe,ready),true);assert.equal(productionCanCraft(recipe,{...ready,materials:{wood:11,ore:5}}),false);});
test('story and Abyss clears feed different settlement materials',()=>{const story=settlementMaterialYield({recLevel:100,boss:false}),abyss=settlementMaterialYield({isAbyss:true,abyssDepth:500,boss:true});assert.ok(story.wood>0);assert.equal(story.veilstone,0);assert.ok(abyss.veilstone>0);assert.ok(abyss.ore>story.ore);});
test('Settlement hooks into hub, S2 evolution, S3 residents, S4 tavern, and S5 production',()=>{const nav=fs.readFileSync(new URL('../js/patches/homeNavigation.js',import.meta.url),'utf8'),rec=fs.readFileSync(new URL('../js/patches/companionRecruitment.js',import.meta.url),'utf8'),core=fs.readFileSync(new URL('../js/patches/settlementCore.js',import.meta.url),'utf8'),tavern=fs.readFileSync(new URL('../js/patches/settlementTavern.js',import.meta.url),'utf8'),production=fs.readFileSync(new URL('../js/patches/settlementProduction.js',import.meta.url),'utf8'),productionUi=fs.readFileSync(new URL('../js/patches/settlementProductionUi.js',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../js/patches/settlementUi.js',import.meta.url),'utf8');assert.match(nav,/goSettlementBtn/);assert.match(nav,/settlementCore/);assert.match(nav,/settlementTavern/);assert.match(nav,/settlementProduction/);assert.match(rec,/recruitChanceBonus/);assert.match(core,/gainPartyCompanionExp/);assert.match(core,/settlementEffectiveLevels/);assert.match(core,/META_KEY='__settlement3'/);assert.match(core,/achievedEras/);assert.match(core,/seenEras/);assert.match(core,/pendingEvolution/);assert.match(core,/consumeSettlementEvolution/);assert.match(core,/seenResidentEvents/);assert.match(core,/pendingResidentEvents/);assert.match(core,/settlementResidents/);assert.match(core,/consumeSettlementResidentEvent/);assert.doesNotMatch(core,/resident.*dead|dead.*resident|removeSettlementResident/i);assert.match(tavern,/settlementTavernUnlocked/);assert.match(tavern,/settlementTavernRumors/);assert.match(tavern,/settlementTavernRequests/);assert.match(tavern,/claimSettlementTavernRequest/);assert.match(tavern,/claimedRequests/);assert.match(production,/settlementProductionUnlocked/);assert.match(production,/settlementProductionGoods/);assert.match(production,/craftSettlementProduction/);assert.doesNotMatch(production,/setInterval|Date\.now|daily|idle/i);assert.match(productionUi,/data-production-facility/);assert.match(productionUi,/data-production-recipe/);assert.match(productionUi,/自動収入・毎日回収・新通貨は追加しない/);assert.match(ui,/SETTLEMENT_AREA_GROUPS/);assert.match(ui,/data-settlement-area/);assert.match(ui,/data-settlement-era/);assert.match(ui,/data-settlement-residents/);assert.match(ui,/data-settlement-resident/);assert.match(ui,/settlementResidentOverlay/);assert.match(ui,/NEW RESIDENT/);assert.match(ui,/data-settlement-tavern/);assert.match(ui,/data-tavern-rumor/);assert.match(ui,/data-tavern-request/);assert.match(ui,/Story必須情報をランダム抽選には置かない/);});
