import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { RESEARCH_DOMAINS,RESEARCH_UNLOCK_HALL_LEVEL,buildResearchCodexReport,buildResearchOutlook,researchTier } from '../js/data/settlementResearch.js';

test('Settlement S7 research unlocks at Trade Town and exposes five observed-data domains',()=>{assert.equal(RESEARCH_UNLOCK_HALL_LEVEL,10);assert.deepEqual(RESEARCH_DOMAINS.map(x=>x.id),['taxonomy','affinity','elite','rare','boss']);assert.equal(researchTier(0),0);assert.equal(researchTier(1),1);assert.equal(researchTier(5),2);assert.equal(researchTier(15),3);});

test('Settlement S7 report ignores unseen Codex entries even when hidden fields contain data',()=>{const report=buildResearchCodexReport([{seen:false,analyzed:true,observedEliteAffixes:['SECRET'],observedRareBehaviors:['SECRET_RARE'],observedAffinities:{fire:'weak'},bossPhaseKnown:true},{seen:true,roleKnown:true,behaviorKnown:true,observedSkills:['火球'],observedAffinities:{ice:'weak'},observedEliteAffixes:['硬化'],observedRareBehaviors:['暴走'],bossPhase2Observed:true}]);assert.equal(report.seenCount,1);assert.equal(report.analyzedCount,0);assert.deepEqual(report.domains.elite.details.observed,['硬化']);assert.deepEqual(report.domains.rare.details.observed,['暴走']);assert.deepEqual(Object.keys(report.domains.affinity.details.affinities),['ice']);assert.equal(report.domains.boss.details.observed,1);assert.ok(!JSON.stringify(report).includes('SECRET'));});

test('Settlement S7 outlook only renders explicitly supplied observed World Event and unlocked Deep Survey data',()=>{assert.deepEqual(buildResearchOutlook({}),[]);const outlook=buildResearchOutlook({worldEvent:{text:'観測中'},deepSurveys:[{id:'known',name:'既知領域',hint:'既知の兆候'}]});assert.ok(outlook.some(x=>x.id==='world_event'&&x.text==='観測中'));assert.ok(outlook.some(x=>x.id==='survey:known'&&x.text==='既知の兆候'));});

test('Settlement S7 runtime never imports enemy master catalogs to reveal unseen knowledge',()=>{const runtime=fs.readFileSync(new URL('../js/patches/settlementResearch.js',import.meta.url),'utf8'),ui=fs.readFileSync(new URL('../js/patches/settlementResearchUi.js',import.meta.url),'utf8'),nav=fs.readFileSync(new URL('../js/patches/homeNavigation.js',import.meta.url),'utf8');assert.match(runtime,/__settlement3/);assert.match(runtime,/meta\.research/);assert.match(runtime,/monsterCodex/);assert.match(runtime,/deepSurveyUnlocked/);assert.doesNotMatch(runtime,/enemyCombatProfile|enemyAffinityProfile|ENEMIES|MONSTERS|enemyRole/);assert.doesNotMatch(runtime,/setInterval|setTimeout|daily|Date\.now/);assert.match(ui,/data-settlement-research/);assert.match(ui,/data-research-domain/);assert.match(ui,/未遭遇情報は研究所だけでは開示されない/);assert.match(nav,/settlementResearch\.js/);assert.match(nav,/settlementResearchUi\.js/);assert.doesNotMatch(nav,/goResearchBtn/);});
