import { state } from '../state.js';
import { Audio_ } from '../audio.js';
import { buildAbyssStage } from '../data/abyss.js';
import { ABYSS_ENDGAME_MILESTONES } from '../data/abyssEndgame.js';
import { ALL_ABYSS_TREE_NODES, abyssTreeNodeCostFor } from '../data/abyssTree.js';
import { maxAbyssPactsForDepth } from '../data/abyssPacts.js';
let abyssActiveTab='challenge';
export function initAbyssTabs(){document.querySelectorAll('#abyssScreen .tab-btn').forEach(btn=>btn.addEventListener('click',()=>{Audio_.tap();abyssActiveTab=btn.dataset.atab;syncAbyssTabs();}));}
function syncAbyssTabs(){document.querySelectorAll('#abyssScreen .tab-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.atab===abyssActiveTab));document.getElementById('abyssHint').classList.toggle('hidden',abyssActiveTab!=='challenge');document.getElementById('abyssList').classList.toggle('hidden',abyssActiveTab!=='challenge');document.getElementById('abyssTreeContent').classList.toggle('hidden',abyssActiveTab!=='tree');document.getElementById('abyssShardText').textContent=`🔹 ${state.data.abyssShards}`;if(abyssActiveTab==='tree')renderAbyssTree();}
export function abyssVisibleDepths(bestDepth){const best=Math.max(0,Math.floor(Number(bestDepth)||0));const next=best+1;const keep=new Set();const start=Math.max(1, next - 39);for(let d=start;d<=next;d++)keep.add(d);keep.add(1);for(const m of ABYSS_ENDGAME_MILESTONES)if(m.depth<=next)keep.add(m.depth);return [...keep].sort((a,b)=>b-a);}
function renderPacts(list,depth,onRefresh){const box=document.createElement('div');box.className='forge-card';const max=maxAbyssPactsForDepth(depth),active=state.activeAbyssPacts(depth);box.innerHTML=`<div class="forge-card-top"><div class="forge-card-name">⚖️ 深淵盟約</div><strong>${active.length}/${max}　危険度 ${state.abyssPactDanger(depth)}</strong></div><div class="forge-card-sub">自分で不利条件を追加して報酬を上げる。250階で2枠、1000階で3枠。</div>${state.abyssPacts.map(p=>`<button class="btn-sub" data-pact="${p.id}" style="width:100%;margin-top:6px;">${active.includes(p.id)?'✓ ':''}${p.name} — ${p.desc}</button>`).join('')}`;box.querySelectorAll('[data-pact]').forEach(b=>b.addEventListener('click',()=>{if(state.toggleAbyssPact(b.dataset.pact,depth)){Audio_.tap();onRefresh();}}));list.appendChild(box);}
export function renderAbyssList(onPick){const list=document.getElementById('abyssList');list.innerHTML='';const best=state.data.abyssBestDepth,maxShown=best+1,depths=abyssVisibleDepths(best);renderPacts(list,maxShown,()=>renderAbyssList(onPick));for(let i=0;i<depths.length;i++){const depth=depths[i],prev=i>0?depths[i-1]:null;if(prev!=null&&prev-depth>1){const gap=document.createElement('div');gap.className='hint';gap.style.textAlign='center';gap.textContent=`⋯ ${prev-depth-1}階省略 ⋯`;list.appendChild(gap);}const pacts=depth===maxShown?state.activeAbyssPacts(depth):[],stage=buildAbyssStage(depth,pacts),isNext=depth===maxShown,cleared=depth<=best,card=document.createElement('div');card.className='stage-card'+(stage.boss?' boss':'');const mod=stage.modifiers.length?`<div class="rec">${stage.modifiers.map(m=>m.name).join(' ／ ')}</div>`:'',pact=stage.abyssPacts.length?`<div class="rec">⚖️ ${stage.abyssPacts.map(p=>p.name).join(' ／ ')}　危険度${stage.abyssPactDanger}</div>`:'';card.innerHTML=`<div><div class="name">${stage.name}${isNext?'　<span style="color:var(--accent)">NEW</span>':''}</div><div class="rec">推奨Lv ${stage.recLevel.toLocaleString()} ／ 目標IP ${stage.itemPowerTarget.toLocaleString()}</div><div class="rec">${stage.abyssEra}</div>${mod}${pact}</div><div class="cleared">${cleared?'★':''}</div>`;card.addEventListener('click',()=>{Audio_.tap();onPick(stage);});list.appendChild(card);}syncAbyssTabs();}
function renderAbyssTree(){const content=document.getElementById('abyssTreeContent');content.innerHTML='';const hint=document.createElement('p');hint.className='hint';hint.textContent='深淵の欠片は、深淵のエリート撃破・ボスフロア踏破で入手できる。深淵限定の永続強化に使う（覚醒しても失われない）。';content.appendChild(hint);for(const node of ALL_ABYSS_TREE_NODES)content.appendChild(renderNode(node));}
function renderNode(node){const rank=state.abyssTreeNodeRank(node.id),maxed=rank>=node.maxRank,cost=abyssTreeNodeCostFor(node,rank),can=state.canBuyAbyssTreeNode(node.id),current=node.pctPerRank?`現在 +${Math.round(rank*node.pctPerRank*1000)/10}%`:`現在 ${rank>0?'習得済み':'未習得'}`,card=document.createElement('div');card.className='forge-card';card.innerHTML=`<div class="forge-card-top"><div class="forge-card-name">${node.name}${node.big?'<span class="mastered-badge">★大型</span>':''}</div><div>Lv.${rank}/${node.maxRank}</div></div><div class="forge-card-sub">${node.desc}（${current}）</div><button class="forge-card-btn" ${maxed||!can?'disabled':''}>${maxed?'MAX':`強化する（🔹${cost}）`}</button>`;card.querySelector('button').addEventListener('click',()=>{if(state.buyAbyssTreeNode(node.id)){Audio_.pickup();syncAbyssTabs();}});return card;}
