import { state } from '../state.js';
import { Audio_ } from '../audio.js';
import { buildAbyssStage } from '../data/abyss.js';
import { abyssRouteChoices } from '../data/abyssRoutes.js';
import { buildSecretRealmStage } from '../data/secretRealms.js';
import { RAID_BOSSES, buildRaidStage, raidBossUnlocked } from '../data/raidBosses.js';
import { ABYSS_ENDGAME_MILESTONES } from '../data/abyssEndgame.js';
import { ALL_ABYSS_TREE_NODES, abyssTreeNodeCostFor } from '../data/abyssTree.js';
import { maxAbyssPactsForDepth } from '../data/abyssPacts.js';
let abyssActiveTab='challenge';
export function initAbyssTabs(){document.querySelectorAll('#abyssScreen .tab-btn').forEach(btn=>btn.addEventListener('click',()=>{Audio_.tap();abyssActiveTab=btn.dataset.atab;syncAbyssTabs();}));}
function syncAbyssTabs(){document.querySelectorAll('#abyssScreen .tab-btn').forEach(btn=>btn.classList.toggle('active',btn.dataset.atab===abyssActiveTab));document.getElementById('abyssHint').classList.toggle('hidden',abyssActiveTab!=='challenge');document.getElementById('abyssList').classList.toggle('hidden',abyssActiveTab!=='challenge');document.getElementById('abyssTreeContent').classList.toggle('hidden',abyssActiveTab!=='tree');document.getElementById('abyssShardText').textContent=`🔹 ${state.data.abyssShards}`;if(abyssActiveTab==='tree')renderAbyssTree();}
export function abyssVisibleDepths(bestDepth){const best=Math.max(0,Math.floor(Number(bestDepth)||0));const next=best+1;const keep=new Set();const start=Math.max(1,next - 39);for(let d=start;d<=next;d++)keep.add(d);keep.add(1);for(const m of ABYSS_ENDGAME_MILESTONES)if(m.depth<=next)keep.add(m.depth);return[...keep].sort((a,b)=>b-a);}

function renderRaids(list,onPick){
  const heading=document.createElement('div');heading.className='section-heading';heading.textContent='RAID — 準備して挑む大規模Boss';list.appendChild(heading);
  for(const raid of RAID_BOSSES){
    const unlocked=raidBossUnlocked(raid,state.data.abyssBestDepth),cleared=state.isStageCleared(raid.id),stage=buildRaidStage(raid.id),card=document.createElement('div');
    card.className='stage-card boss'+(!unlocked?' locked':'');
    const tags=raid.dangerTags.join(' / '),unlockText=`深淵 ${raid.requiredAbyssDepth}F 到達で解放`;
    card.innerHTML=`<div><div class="name">${unlocked?'RAID ': '🔒 '}${unlocked?raid.shortName:'未観測の強敵'}</div><div class="rec">${unlocked?`推奨Lv ${stage.recLevel.toLocaleString()} ／ 目標IP ${stage.itemPowerTarget.toLocaleString()}`:unlockText}</div>${unlocked?`<div class="rec">危険: ${tags}</div><div class="rec">${raid.mechanic}</div>`:''}</div><div class="cleared">${cleared?'★':unlocked?'→':''}</div>`;
    if(unlocked)card.addEventListener('click',()=>{Audio_.tap();onPick(stage);});
    list.appendChild(card);
  }
}

function renderExploration(list,onPick,onRefresh){for(const site of state.explorationSites||[]){const p=state.explorationProgress(site.id);if(!p||p.state==='hidden')continue;const card=document.createElement('div');card.className='forge-card';const title=p.unlocked?`🚪 ${site.realmName}`:`🔎 ${site.discoveredName}`,count=site.fragmentsRequired?`${p.fragments}/${site.fragmentsRequired}`:'';let body=p.inspected?`${site.inspectText.join('<br>')}<br><strong>手掛かり ${count}</strong>`:'場所は見つけた。しかし、まだ詳しく調べていない。';if(site.finalGoal)body+=`<br><strong>鍵 ${p.fragments}/${site.fragmentsRequired}</strong>`;if(p.unlocked&&site.realm)body+=`<br>${site.unlockedText}<br>推奨Lv ${site.realm.recLevel.toLocaleString()} / 目標IP ${site.realm.itemPowerTarget.toLocaleString()}<br>${site.realm.rule}<br>${site.realm.rewardHint}`;card.innerHTML=`<div class="forge-card-top"><div class="forge-card-name">${title}</div><div>${count}</div></div><div class="forge-card-sub">${body}</div><div class="explore-actions" style="display:flex;gap:6px;margin-top:8px;"></div>`;const actions=card.querySelector('.explore-actions');if(!p.inspected){const b=document.createElement('button');b.className='btn-sub';b.textContent='調べる';b.addEventListener('click',()=>{if(state.inspectExplorationSite(site.id)){Audio_.tap();onRefresh();}});actions.appendChild(b);}if(p.unlocked&&site.realm){const b=document.createElement('button');b.className='forge-card-btn';b.textContent='異界へ入る';b.addEventListener('click',()=>{Audio_.tap();onPick(buildSecretRealmStage(site.realm.id));});actions.appendChild(b);}list.appendChild(card);}}
function renderPacts(list,depth,onRefresh){const box=document.createElement('div');box.className='forge-card';const max=maxAbyssPactsForDepth(depth),active=state.activeAbyssPacts(depth);box.innerHTML=`<div class="forge-card-top"><div class="forge-card-name">⚖️ 深淵盟約</div><strong>${active.length}/${max}　危険度 ${state.abyssPactDanger(depth)}</strong></div><div class="forge-card-sub">大きなRisk/Rewardを選ぶ盟約。250階で2枠、1000階で3枠。</div>${state.abyssPacts.map(p=>`<button class="btn-sub" data-pact="${p.id}" style="width:100%;margin-top:6px;">${active.includes(p.id)?'✓ ':''}${p.name} — ${p.desc}</button>`).join('')}`;box.querySelectorAll('[data-pact]').forEach(b=>b.addEventListener('click',()=>{if(state.toggleAbyssPact(b.dataset.pact,depth)){Audio_.tap();onRefresh();}}));list.appendChild(box);}
function renderChallenges(list,onRefresh){const active=state.activeAbyssChallenges(),box=document.createElement('div');box.className='forge-card';box.innerHTML=`<div class="forge-card-top"><div class="forge-card-name">🔥 深淵への誓約</div><strong>${active.length}個　危険度 +${state.abyssChallengeDanger()}</strong></div><div class="forge-card-sub">Challenge Modifier。好きなだけ不利条件を重ねられる。Riskを自分で盛るほど、狙った上位報酬が増える。</div>${state.abyssChallenges.map(c=>`<button class="btn-sub" data-challenge="${c.id}" style="width:100%;margin-top:6px;">${active.includes(c.id)?'✓ ':''}${c.icon} ${c.name} — ${c.desc}</button>`).join('')}`;box.querySelectorAll('[data-challenge]').forEach(b=>b.addEventListener('click',()=>{if(state.toggleAbyssChallenge(b.dataset.challenge)){Audio_.tap();onRefresh();}}));list.appendChild(box);}
function renderRouteChoices(list,depth,onPick){const veilBreached=state.isStageCleared('20-8'),pacts=state.activeAbyssPacts(depth),challenges=state.activeAbyssChallenges(),heading=document.createElement('div');heading.className='forge-card';heading.innerHTML=`<div class="forge-card-name">分かれ道 — ${depth}階へ</div><div class="forge-card-sub">欲しい報酬と、受け入れる危険を選ぶ。</div>`;list.appendChild(heading);for(const route of abyssRouteChoices(depth,{veilBreached})){const stage=buildAbyssStage(depth,pacts,{routeId:route.id,challengeIds:challenges}),card=document.createElement('div');card.className='stage-card'+(stage.boss?' boss':'');card.innerHTML=`<div><div class="name">${route.icon} ${route.name} <span style="color:var(--accent)">NEW</span></div><div class="rec">${route.desc}</div><div class="rec">☠ ${route.risk}</div><div class="rec">◆ ${route.reward}${route.targetLabel?` ／ 狙い: ${route.targetLabel}`:''}</div><div class="rec">推奨Lv ${stage.recLevel.toLocaleString()} ／ 目標IP ${stage.itemPowerTarget.toLocaleString()}</div>${stage.modifiers.length?`<div class="rec">環境: ${stage.modifiers.map(m=>m.name).join(' ／ ')}</div>`:''}${stage.abyssPacts.length?`<div class="rec">⚖️ ${stage.abyssPacts.map(p=>p.name).join(' ／ ')}　危険度${stage.abyssPactDanger}</div>`:''}${stage.abyssChallenges.length?`<div class="rec">🔥 ${stage.abyssChallenges.map(c=>c.name).join(' ／ ')}　追加危険度${stage.abyssChallengeDanger}</div>`:''}</div><div class="cleared">→</div>`;card.addEventListener('click',()=>{Audio_.tap();onPick(stage);});list.appendChild(card);}}
export function renderAbyssList(onPick){const list=document.getElementById('abyssList');list.innerHTML='';const best=state.data.abyssBestDepth,maxShown=best+1,depths=abyssVisibleDepths(best),refresh=()=>renderAbyssList(onPick);renderRaids(list,onPick);renderExploration(list,onPick,refresh);renderPacts(list,maxShown,refresh);renderChallenges(list,refresh);renderRouteChoices(list,maxShown,onPick);const historyDepths=depths.filter(depth=>depth<=best);for(let i=0;i<historyDepths.length;i++){const depth=historyDepths[i],prev=i>0?historyDepths[i-1]:null;if(prev!=null&&prev-depth>1){const gap=document.createElement('div');gap.className='hint';gap.style.textAlign='center';gap.textContent=`⋯ ${prev-depth-1}階省略 ⋯`;list.appendChild(gap);}const stage=buildAbyssStage(depth,[]),card=document.createElement('div');card.className='stage-card'+(stage.boss?' boss':'');const mod=stage.modifiers.length?`<div class="rec">${stage.modifiers.map(m=>m.name).join(' ／ ')}</div>`:'';card.innerHTML=`<div><div class="name">${stage.name}</div><div class="rec">推奨Lv ${stage.recLevel.toLocaleString()} ／ 目標IP ${stage.itemPowerTarget.toLocaleString()}</div><div class="rec">${stage.abyssEra}</div>${mod}</div><div class="cleared">★</div>`;card.addEventListener('click',()=>{Audio_.tap();onPick(stage);});list.appendChild(card);}syncAbyssTabs();}
function renderAbyssTree(){const content=document.getElementById('abyssTreeContent');content.innerHTML='';const hint=document.createElement('p');hint.className='hint';hint.textContent='深淵の欠片は、深淵のエリート撃破・ボスフロア踏破で入手できる。深淵限定の永続強化に使う（覚醒しても失われない）。';content.appendChild(hint);for(const node of ALL_ABYSS_TREE_NODES)content.appendChild(renderNode(node));}
function renderNode(node){const rank=state.abyssTreeNodeRank(node.id),maxed=rank>=node.maxRank,cost=abyssTreeNodeCostFor(node,rank),can=state.canBuyAbyssTreeNode(node.id),current=node.pctPerRank?`現在 +${Math.round(rank*node.pctPerRank*1000)/10}%`:`現在 ${rank>0?'習得済み':'未習得'}`,card=document.createElement('div');card.className='forge-card';card.innerHTML=`<div class="forge-card-top"><div class="forge-card-name">${node.name}${node.big?'<span class="mastered-badge">★大型</span>':''}</div><div>Lv.${rank}/${node.maxRank}</div></div><div class="forge-card-sub">${node.desc}（${current}）</div><button class="forge-card-btn" ${maxed||!can?'disabled':''}>${maxed?'MAX':`強化する（🔹${cost}）`}</button>`;card.querySelector('button').addEventListener('click',()=>{if(state.buyAbyssTreeNode(node.id)){Audio_.pickup();syncAbyssTabs();}});return card;}
