import { jobsByTier, getJob } from '../data/jobs.js';
import { FUSION_JOBS } from '../data/jobFusionRegistry.js';
import { fusionRoleFor } from '../data/fusionConstellation.js';
import { state } from '../state.js';
import { Audio_ } from '../audio.js';

const ROLE_LABEL={martial:'武闘',arcane:'魔法',support:'支援',utility:'技巧',spellblade:'魔戦',guardian:'守戦',skirmisher:'遊撃',mystic:'神秘',artificer:'錬機',provisioner:'支度',hybrid:'融星'};
let galaxyFilter='all',galaxyQuery='',systemFilter='all',selectedGalaxyFusion=null;
function statusOf(f,m){const n=f.parents.filter(id=>m.has(id)).length;return n===2?'discovered':n===1?'hinted':'hidden';}
function basics(){return jobsByTier('basic');}
function systemPos(i,total){const a=-Math.PI/2+Math.PI*2*i/total;return{x:50+Math.cos(a)*37,y:50+Math.sin(a)*37};}
function fusionPos(f,systems){const ai=systems.findIndex(j=>j.id===f.parents[0]),bi=systems.findIndex(j=>j.id===f.parents[1]),a=systemPos(ai,systems.length),b=systemPos(bi,systems.length),seed=FUSION_JOBS.findIndex(x=>x.id===f.id),jitter=((seed%5)-2)*1.2;return{x:(a.x+b.x)/2+jitter,y:(a.y+b.y)/2-jitter*.55};}
function labelFor(s){return s==='discovered'?'発見済':s==='hinted'?'共鳴候補':'未発見';}
function visibleFusion(f,m){const s=statusOf(f,m);if(galaxyFilter!=='all'&&galaxyFilter!==s)return false;if(systemFilter!=='all'&&!f.parents.includes(systemFilter))return false;if(!galaxyQuery.trim())return true;const q=galaxyQuery.trim().toLowerCase(),parents=f.parents.map(id=>getJob(id)?.name||id).join(' ');return `${s==='hidden'?'':f.name} ${parents} ${ROLE_LABEL[fusionRoleFor(f.id)]||''}`.toLowerCase().includes(q);}
function detail(f,m){if(!f)return'';const s=statusOf(f,m),parents=f.parents.map(id=>getJob(id));return`<aside class="galaxy-focus-card ${s}"><button class="galaxy-close" data-galaxy-close>×</button><span>${labelFor(s)} / ${ROLE_LABEL[fusionRoleFor(f.id)]||'融合'}</span><strong>${s==='hidden'?'？？？？？':f.name}</strong><small>${s==='hidden'?'星はまだ眠っている':parents.map(j=>j?.name).join(' × ')}</small>${s==='hinted'?`<p>${parents.filter(j=>!m.has(j?.id)).map(j=>j?.name).join('・')}をMASTERすると共鳴</p>`:''}${s==='discovered'?`<button class="btn-main" data-open-fusion="${f.id}">Fusion星盤を開く</button>`:''}</aside>`;}
export function renderFusionGalaxy(container,opts={}){const m=state.masteredSet(),systems=basics(),all=FUSION_JOBS,discovered=all.filter(f=>statusOf(f,m)==='discovered').length,hinted=all.filter(f=>statusOf(f,m)==='hinted').length,visible=all.filter(f=>visibleFusion(f,m)),selected=all.find(f=>f.id===selectedGalaxyFusion);container.innerHTML=`<section class="fusion-galaxy"><div class="fusion-galaxy-head"><div><span>FUSION GALAXY</span><strong>共鳴銀河</strong><small>15の基本星系と105の共鳴星。親星を選ぶと星系だけを探索できます。</small></div><div class="fusion-galaxy-count"><b>${discovered}</b>/105<small>発見済 / 候補 ${hinted}</small></div></div><div class="fusion-galaxy-toolbar"><input type="search" value="${galaxyQuery}" placeholder="Fusion・親職・ROLEを検索" data-galaxy-search><div>${[['all','すべて'],['discovered','発見済'],['hinted','候補'],['hidden','未発見']].map(([id,l])=>`<button class="phase8-filter ${galaxyFilter===id?'active':''}" data-galaxy-filter="${id}">${l}</button>`).join('')}</div><div class="galaxy-system-filters"><button class="phase8-filter ${systemFilter==='all'?'active':''}" data-system="all">全星系</button>${systems.map(j=>`<button class="phase8-filter ${systemFilter===j.id?'active':''} ${m.has(j.id)?'mastered':''}" data-system="${j.id}">${m.has(j.id)?'★':'◇'} ${j.name}</button>`).join('')}</div></div><div class="fusion-galaxy-map">${systems.map((j,i)=>{const p=systemPos(i,systems.length);return`<button class="galaxy-system-star ${m.has(j.id)?'mastered':''} ${systemFilter===j.id?'selected':''}" style="left:${p.x}%;top:${p.y}%" data-system="${j.id}"><i></i><span>${j.name}</span></button>`}).join('')}<svg class="galaxy-links" viewBox="0 0 100 100" preserveAspectRatio="none">${visible.filter(f=>statusOf(f,m)!=='hidden').map(f=>{const p=fusionPos(f,systems);return f.parents.map(pid=>{const j=systems.findIndex(x=>x.id===pid),s=systemPos(j,systems.length);return`<line class="${statusOf(f,m)}" x1="${s.x}" y1="${s.y}" x2="${p.x}" y2="${p.y}"></line>`}).join('')}).join('')}</svg>${visible.map(f=>{const s=statusOf(f,m),p=fusionPos(f,systems),role=fusionRoleFor(f.id);return`<button class="galaxy-star ${s} role-${role} ${selectedGalaxyFusion===f.id?'selected':''}" style="left:${p.x}%;top:${p.y}%" data-galaxy-fusion="${f.id}" aria-label="${s==='hidden'?'未発見Fusion':f.name}"><i></i><span>${s==='hidden'?'？？？':f.name}</span></button>`}).join('')}<div class="galaxy-core"><span>FUSION</span><strong>${discovered}</strong><small>DISCOVERED</small></div>${detail(selected,m)}</div><div class="fusion-galaxy-cards">${visible.map(f=>{const s=statusOf(f,m),parents=f.parents.map(id=>getJob(id)?.name||id),role=fusionRoleFor(f.id);return`<button class="galaxy-card ${s}" data-galaxy-fusion="${f.id}"><span class="galaxy-card-status">${labelFor(s)}</span><strong>${s==='hidden'?'？？？？？':f.name}</strong><small>${s==='hidden'?'星はまだ眠っている':parents.join(' × ')}</small>${s!=='hidden'?`<em>${ROLE_LABEL[role]||'融合'}</em>`:''}</button>`}).join('')}</div></section>`;
const search=container.querySelector('[data-galaxy-search]');if(search)search.addEventListener('input',()=>{galaxyQuery=search.value;renderFusionGalaxy(container,opts)});for(const b of container.querySelectorAll('[data-galaxy-filter]'))b.addEventListener('click',()=>{galaxyFilter=b.dataset.galaxyFilter;Audio_.tap();renderFusionGalaxy(container,opts)});for(const b of container.querySelectorAll('[data-system]'))b.addEventListener('click',()=>{systemFilter=b.dataset.system;selectedGalaxyFusion=null;Audio_.tap();renderFusionGalaxy(container,opts)});for(const b of container.querySelectorAll('[data-galaxy-fusion]'))b.addEventListener('click',()=>{selectedGalaxyFusion=b.dataset.galaxyFusion;Audio_.tap();renderFusionGalaxy(container,opts)});container.querySelector('[data-galaxy-close]')?.addEventListener('click',()=>{selectedGalaxyFusion=null;renderFusionGalaxy(container,opts)});container.querySelector('[data-open-fusion]')?.addEventListener('click',()=>opts.onOpenFusion?.(selectedGalaxyFusion));}
