import { jobsByTier, getJob } from '../data/jobs.js';
import { FUSION_JOBS } from '../data/jobFusionRegistry.js';
import { fusionRoleFor } from '../data/fusionConstellation.js';
import { state } from '../state.js';
import { Audio_ } from '../audio.js';

const ROLE_LABEL={martial:'武闘',arcane:'魔法',support:'支援',utility:'技巧',spellblade:'魔戦',guardian:'守戦',skirmisher:'遊撃',mystic:'神秘',artificer:'錬機',provisioner:'支度',hybrid:'融星'};
let galaxyFilter='all',galaxyQuery='';
function statusOf(f,m){const n=f.parents.filter(id=>m.has(id)).length;return n===2?'discovered':n===1?'hinted':'hidden';}
function point(i,total){const ring=i%3,radius=[25,36,45][ring],angle=-Math.PI/2+(Math.PI*2*i/total)*3;return{x:50+Math.cos(angle)*radius,y:50+Math.sin(angle)*radius};}
function labelFor(status){return status==='discovered'?'発見済':status==='hinted'?'共鳴候補':'未発見';}
function visibleFusion(f,m){const status=statusOf(f,m);if(galaxyFilter!=='all'&&galaxyFilter!==status)return false;if(!galaxyQuery.trim())return true;const q=galaxyQuery.trim().toLowerCase(),parents=f.parents.map(id=>getJob(id)?.name||id).join(' ');return `${status==='hidden'?'':f.name} ${parents} ${ROLE_LABEL[fusionRoleFor(f.id)]||''}`.toLowerCase().includes(q);}
export function renderFusionGalaxy(container){const m=state.masteredSet(),all=FUSION_JOBS,discovered=all.filter(f=>statusOf(f,m)==='discovered').length,hinted=all.filter(f=>statusOf(f,m)==='hinted').length,visible=all.filter(f=>visibleFusion(f,m));container.innerHTML=`<section class="fusion-galaxy"><div class="fusion-galaxy-head"><div><span>FUSION GALAXY</span><strong>共鳴銀河</strong><small>15の基本星から生まれる105のFusionを俯瞰する。</small></div><div class="fusion-galaxy-count"><b>${discovered}</b>/105<small>発見済 / 候補 ${hinted}</small></div></div><div class="fusion-galaxy-toolbar"><input type="search" value="${galaxyQuery}" placeholder="Fusion・親職・ROLEを検索" data-galaxy-search><div>${[['all','すべて'],['discovered','発見済'],['hinted','候補'],['hidden','未発見']].map(([id,l])=>`<button class="phase8-filter ${galaxyFilter===id?'active':''}" data-galaxy-filter="${id}">${l}</button>`).join('')}</div></div><div class="fusion-galaxy-map">${visible.map((f,i)=>{const s=statusOf(f,m),p=point(i,Math.max(visible.length,1)),role=fusionRoleFor(f.id),parents=f.parents.map(id=>getJob(id)?.name||id);return`<button class="galaxy-star ${s} role-${role}" style="left:${p.x}%;top:${p.y}%" data-galaxy-fusion="${f.id}" aria-label="${s==='hidden'?'未発見Fusion':f.name}"><i></i><span>${s==='hidden'?'？？？':f.name}</span></button>`}).join('')}<div class="galaxy-core"><span>FUSION</span><strong>${discovered}</strong><small>DISCOVERED</small></div></div><div class="fusion-galaxy-cards">${visible.map(f=>{const s=statusOf(f,m),parents=f.parents.map(id=>getJob(id)?.name||id),role=fusionRoleFor(f.id);return`<article class="galaxy-card ${s}"><span class="galaxy-card-status">${labelFor(s)}</span><strong>${s==='hidden'?'？？？？？':f.name}</strong><small>${s==='hidden'?'星はまだ眠っている':parents.join(' × ')}</small>${s!=='hidden'?`<em>${ROLE_LABEL[role]||'融合'}</em>`:''}</article>`}).join('')}</div></section>`;
const search=container.querySelector('[data-galaxy-search]');if(search)search.addEventListener('input',()=>{galaxyQuery=search.value;renderFusionGalaxy(container)});for(const b of container.querySelectorAll('[data-galaxy-filter]'))b.addEventListener('click',()=>{galaxyFilter=b.dataset.galaxyFilter;Audio_.tap();renderFusionGalaxy(container)});for(const b of container.querySelectorAll('[data-galaxy-fusion]'))b.addEventListener('click',()=>{const f=all.find(x=>x.id===b.dataset.galaxyFusion);if(!f)return;Audio_.tap();const card=[...container.querySelectorAll('.galaxy-card')].find(c=>c.querySelector('strong')?.textContent===(statusOf(f,m)==='hidden'?'？？？？？':f.name));card?.scrollIntoView({behavior:'smooth',block:'nearest'});});}
