import { jobsByTier, getJob } from '../data/jobs.js';
import { FUSION_JOBS, getFusionJobByParents, getFusionJobById } from '../data/jobFusionRegistry.js';
import { constellationTreeFor } from '../data/jobConstellationTrees.js';
import { fusionConstellationFor, fusionRoleFor } from '../data/fusionConstellation.js';
import { state } from '../state.js';
import { Audio_ } from '../audio.js';

let selectedBasicId='warrior',selectedFusionId=null,roleFilter='all';
const CENTER=500,RADIUS=360;
const ROLE_LABEL=Object.freeze({martial:'武闘',arcane:'魔法',support:'支援',utility:'技巧',spellblade:'魔戦',guardian:'守戦',skirmisher:'遊撃',mystic:'神秘',artificer:'錬機',provisioner:'支度',hybrid:'融星'});
function roleLabel(id){return ROLE_LABEL[fusionRoleFor(id)]||'融合';}
function posFor(i,total){const a=-Math.PI/2+Math.PI*2*i/total;return{x:CENTER+Math.cos(a)*RADIUS,y:CENTER+Math.sin(a)*RADIUS};}
function basicJobs(){return jobsByTier('basic');}
function discoveryState(f,m){const masteredCount=f.parents.filter(id=>m.has(id)).length;return masteredCount===2?'discovered':masteredCount===1?'hinted':'hidden';}
function fusionSummary(id,m){const rank={discovered:0,hinted:1,hidden:2};return FUSION_JOBS.filter(f=>f.parents.includes(id)).map(f=>({...f,discovery:discoveryState(f,m)})).sort((a,b)=>rank[a.discovery]-rank[b.discovery]||a.name.localeCompare(b.name,'ja'));}
function buildLines(jobs,id,m){const si=jobs.findIndex(j=>j.id===id);if(si<0)return'';const from=posFor(si,jobs.length);return jobs.map((j,i)=>{if(j.id===id)return'';const f=getFusionJobByParents(id,j.id);if(!f)return'';const to=posFor(i,jobs.length),both=m.has(id)&&m.has(j.id),one=m.has(id)||m.has(j.id);return`<line class="constellation-link ${both?'active':one?'hinted':'locked'}" x1="${from.x}" y1="${from.y}" x2="${to.x}" y2="${to.y}"></line>`}).join('');}
function starButtons(jobs,m){return jobs.map((j,i)=>{const p=posFor(i,jobs.length),mastered=m.has(j.id),selected=j.id===selectedBasicId,prog=state.jobProgress(j.id);return`<button class="constellation-star ${mastered?'mastered':''} ${selected?'selected':''}" data-basic-job="${j.id}" style="left:${p.x/10}%;top:${p.y/10}%"><span class="constellation-star-core">${mastered?'★':'◇'}</span><span class="constellation-star-label">${j.name}</span><span class="constellation-star-level">Lv.${prog.level}</span></button>`}).join('');}
function fusionList(job,m){const rows=fusionSummary(job.id,m);const discovered=rows.filter(f=>f.discovery==='discovered');const roles=[...new Set(discovered.map(f=>fusionRoleFor(f.id)))];if(roleFilter!=='all'&&!roles.includes(roleFilter))roleFilter='all';const filters=roles.length>1?`<div class="fusion-role-filters"><button class="fusion-role-filter ${roleFilter==='all'?'active':''}" data-role-filter="all">すべて</button>${roles.map(r=>`<button class="fusion-role-filter role-${r} ${roleFilter===r?'active':''}" data-role-filter="${r}">${ROLE_LABEL[r]}</button>`).join('')}</div>`:'';const visible=rows.filter(f=>f.discovery!=='discovered'||roleFilter==='all'||fusionRoleFor(f.id)===roleFilter);return filters+visible.map(f=>{const partnerId=f.parents.find(id=>id!==job.id),partner=getJob(partnerId);if(f.discovery==='discovered'){const role=fusionRoleFor(f.id);return`<button class="constellation-fusion-row discovered role-${role} ${selectedFusionId===f.id?'selected':''}" data-fusion-job="${f.id}"><span class="fusion-status">✦</span><span class="fusion-main"><strong>${f.name}</strong><small>${job.name} × ${partner.name}</small></span><span class="fusion-role-badge role-${role}">${roleLabel(f.id)}</span><span class="fusion-state">${state.activeFusionId()===f.id?'ACTIVE':'発見'}</span></button>`;}if(f.discovery==='hinted'){const missing=getJob(f.parents.find(id=>!m.has(id)));return`<button class="constellation-fusion-row hinted" data-partner-job="${partnerId}"><span class="fusion-status">◇</span><span class="fusion-main"><strong>？？？？？</strong><small>${missing?.name||'もう一つの基本職'}をMASTERすると共鳴</small></span><span class="fusion-state">未完成</span></button>`;}return`<div class="constellation-fusion-row locked"><span class="fusion-status">·</span><span class="fusion-main"><strong>？？？？？</strong><small>星はまだ眠っている</small></span><span class="fusion-state">未発見</span></div>`}).join('');}
function skillTree(job){const tree=constellationTreeFor(job.id),available=state.constellationPointsAvailable(job.id),earned=state.constellationPointsEarned(job.id);return`<div class="constellation-skill-head"><div><strong>${job.name} Skill Tree</strong><small>Job LvでSP獲得。接続済みノードから順に取得。</small></div><span>SP ${available}/${earned}</span></div><div class="constellation-skill-tree">${tree.map(n=>{const s=state.constellationNodeStatus(job.id,n.id),cls=s.bought?'bought':s.canBuy?'available':'locked',label=s.bought?'取得済':n.kind==='master'&&!s.masteryOk?'MASTER必要':s.canBuy?`${n.cost} SP`:'前提未達';return`<button class="constellation-skill-node ${cls} ${n.kind}" data-skill-node="${n.id}" ${s.canBuy?'':'disabled'}><span class="skill-node-kind">${n.kind.toUpperCase()}</span><strong>${n.name}</strong><small>${n.desc}</small><em>${label}</em></button>`}).join('')}</div>`;}
function fusionKindLabel(kind){return kind==='fusionTrait'?'CORE TRAIT':kind==='fusionSpecialization'?'SPECIALIZE':kind==='fusionKeystone'?'KEYSTONE':'ULTIMATE';}
function fusionGridStyle(n){if(n.kind==='fusionTrait'||n.kind==='fusionUltimate')return'grid-column:1/-1;';if(n.id.endsWith('_path_a')||n.id.endsWith('_keystone'))return'grid-column:1;';return'grid-column:2;';}
function fusionPanel(){const f=getFusionJobById(selectedFusionId);if(!f||!state.isFusionDiscovered(f.id))return'';const tree=fusionConstellationFor(f.id),earned=state.fusionPointsEarned(f.id),available=state.fusionPointsAvailable(f.id),active=state.activeFusionId()===f.id,parents=f.parents.map(id=>getJob(id)?.name||id).join(' × '),role=fusionRoleFor(f.id),summary=state.fusionBuildSummary?.(f.id),hasSpent=state.fusionPointsSpent(f.id)>0;return`<div class="constellation-panel fusion-detail role-${role}"><div class="constellation-skill-head"><div><strong>✦ ${f.name} <span class="fusion-role-badge role-${role}">${roleLabel(f.id)}</span></strong><small>${parents} / 親職Lv5ごとに共鳴SPを獲得${summary?.path?` / ${summary.path}`:''}</small></div><span>FSP ${available}/${earned}</span></div><div class="fusion-role-summary">ROLE / ${roleLabel(f.id)}<small>COREから左右どちらかの星路を選択 → Keystone → Ultimate</small></div><div class="constellation-fusion-actions" style="display:grid;grid-template-columns:1fr ${hasSpent?'auto':'0'};gap:6px;padding:8px"><button class="job-view-tab ${active?'active':''}" data-activate-fusion="${f.id}">${active?'ACTIVE':'この共鳴を有効化'}</button>${hasSpent?`<button class="btn-sub" data-reset-fusion="${f.id}">星路リセット</button>`:''}</div><div class="constellation-skill-tree fusion-branch-tree" style="grid-template-columns:1fr 1fr;position:relative">${tree.map(n=>{const s=state.fusionNodeStatus(f.id,n.id),cls=s.bought?'bought':s.canBuy?'available':'locked',blocked=!s.bought&&!s.canBuy&&s.exclusiveOk===false?'反対側を選択済':!s.bought&&!s.canBuy?'前提/FSP不足':'取得済';return`<button style="${fusionGridStyle(n)}" class="constellation-skill-node ${cls} ${n.kind}" data-fusion-node="${n.id}" ${s.canBuy?'':'disabled'}><span class="skill-node-kind">${fusionKindLabel(n.kind)}</span><strong>${n.name}</strong><small>${n.desc}</small><em>${s.bought?'取得済':s.canBuy?`${n.cost} FSP`:`${blocked}`}</em></button>`}).join('')}</div></div>`;}
export function renderJobConstellation(container){const jobs=basicJobs();if(!jobs.some(j=>j.id===selectedBasicId))selectedBasicId=jobs[0]?.id||'warrior';const m=state.masteredSet(),job=getJob(selectedBasicId)||jobs[0],mastered=m.has(job.id),discovered=FUSION_JOBS.filter(f=>f.parents.every(id=>m.has(id))).length,masteredBasics=jobs.filter(j=>m.has(j.id)).length;if(selectedFusionId&&!state.isFusionDiscovered(selectedFusionId))selectedFusionId=null;container.innerHTML=`<div class="constellation-shell"><div class="constellation-summary"><div><span class="constellation-kicker">SKILL CONSTELLATION</span><strong>職業星盤</strong></div><div class="constellation-count">基本星 ${masteredBasics}/15<br><span>共鳴 ${discovered}/105</span></div></div><p class="constellation-hint">基本星を育成し、MASTERした2職を共鳴。Fusion Traitから二つのSpecializationのどちらかを選び、Keystone → Ultimateへ星路を伸ばします。有効化できる共鳴は1つです。</p><div class="constellation-board-wrap"><div class="constellation-board"><svg class="constellation-svg" viewBox="0 0 1000 1000"><circle class="constellation-orbit" cx="500" cy="500" r="360"></circle>${buildLines(jobs,job.id,m)}</svg>${starButtons(jobs,m)}<div class="constellation-center ${mastered?'mastered':''}"><span>${mastered?'MASTER STAR':'JOB STAR'}</span><strong>${job.name}</strong><small>${mastered?'共鳴可能':'育成中'}</small></div></div></div><div class="constellation-panel constellation-skill-panel">${skillTree(job)}</div>${fusionPanel()}<div class="constellation-panel"><div class="constellation-panel-head"><strong>${job.name}から伸びる星路</strong><span>${mastered?'★ MASTER':'未MASTER'}</span></div><div class="constellation-fusion-list">${fusionList(job,m)}</div></div></div>`;
for(const b of container.querySelectorAll('[data-basic-job]'))b.addEventListener('click',()=>{Audio_.tap();selectedBasicId=b.dataset.basicJob;selectedFusionId=null;roleFilter='all';renderJobConstellation(container)});
for(const b of container.querySelectorAll('[data-partner-job]'))b.addEventListener('click',()=>{Audio_.tap();selectedBasicId=b.dataset.partnerJob;selectedFusionId=null;roleFilter='all';renderJobConstellation(container)});
for(const b of container.querySelectorAll('[data-fusion-job]'))b.addEventListener('click',()=>{Audio_.tap();selectedFusionId=b.dataset.fusionJob;renderJobConstellation(container)});
for(const b of container.querySelectorAll('[data-role-filter]'))b.addEventListener('click',()=>{Audio_.tap();roleFilter=b.dataset.roleFilter;renderJobConstellation(container)});
for(const b of container.querySelectorAll('[data-skill-node]:not([disabled])'))b.addEventListener('click',()=>{Audio_.tap();if(state.buyConstellationNode(job.id,b.dataset.skillNode))renderJobConstellation(container)});
for(const b of container.querySelectorAll('[data-fusion-node]:not([disabled])'))b.addEventListener('click',()=>{Audio_.tap();if(state.buyFusionNode(selectedFusionId,b.dataset.fusionNode))renderJobConstellation(container)});
for(const b of container.querySelectorAll('[data-activate-fusion]'))b.addEventListener('click',()=>{Audio_.tap();state.setActiveFusion(b.dataset.activateFusion);renderJobConstellation(container)});
for(const b of container.querySelectorAll('[data-reset-fusion]'))b.addEventListener('click',()=>{Audio_.tap();if(state.resetFusionConstellation?.(b.dataset.resetFusion))renderJobConstellation(container)});
}
