import { jobsByTier, isUnlocked, unlockRequirementText, TIERS } from '../data/jobsPhase8.js';
import { WEAPON_TYPES } from '../data/equipment.js';
import { state } from '../state.js';
import { Audio_ } from '../audio.js';
import { renderJobConstellation } from './jobConstellation.js';

const TIER_LABELS={all:'すべて',basic:'基本',advanced:'融合',special:'特級',hero:'勇者'};
let jobView='constellation',tierFilter='all',statusFilter='all',query='';

function tabs(){return `<div class="job-view-tabs"><button class="job-view-tab ${jobView==='constellation'?'active':''}" data-job-view="constellation">✦ 星盤</button><button class="job-view-tab ${jobView==='list'?'active':''}" data-job-view="list">職業一覧</button></div>`;}
function toolbar(all,mastered){const unlocked=all.filter(j=>isUnlocked(j.id,mastered)).length;return `<div class="phase8-job-toolbar"><div class="phase8-job-stats"><strong>${all.length} JOBS</strong><span>解放 ${unlocked}</span><span>MASTER ${all.filter(j=>state.isMastered(j.id)).length}</span></div><input class="phase8-job-search" type="search" value="${query}" placeholder="職業名・親職で検索"><div class="phase8-filter-row">${Object.entries(TIER_LABELS).map(([id,label])=>`<button class="phase8-filter ${tierFilter===id?'active':''}" data-tier="${id}">${label}</button>`).join('')}</div><div class="phase8-filter-row"><button class="phase8-filter ${statusFilter==='all'?'active':''}" data-status="all">全状態</button><button class="phase8-filter ${statusFilter==='unlocked'?'active':''}" data-status="unlocked">解放済</button><button class="phase8-filter ${statusFilter==='mastered'?'active':''}" data-status="mastered">MASTER</button><button class="phase8-filter ${statusFilter==='locked'?'active':''}" data-status="locked">未解放</button></div></div>`;}

function matches(job,mastered){if(tierFilter!=='all'&&job.tier!==tierFilter)return false;const unlocked=isUnlocked(job.id,mastered),m=state.isMastered(job.id);if(statusFilter==='unlocked'&&!unlocked)return false;if(statusFilter==='mastered'&&!m)return false;if(statusFilter==='locked'&&unlocked)return false;if(query.trim()){const q=query.trim().toLowerCase(),parents=(job.requires||[]).map(id=>jobsByTier('basic').find(j=>j.id===id)?.name||id).join(' ');if(!`${job.name} ${job.desc||''} ${parents}`.toLowerCase().includes(q))return false;}return true;}

function compactCard(job,mastered){const unlocked=isUnlocked(job.id,mastered),current=!state.data.activeSecretJobId&&job.id===state.currentJobId,masteredJob=state.isMastered(job.id),prog=state.jobProgress(job.id),tierInfo=TIERS[job.tier],blocked=!current&&unlocked&&!state.canChangeAwayFromCurrent();const parents=(job.requires||[]).map(id=>jobsByTier('basic').find(j=>j.id===id)?.name||id);let action=current?'使用中':!unlocked?'LOCK':blocked?'転職不可':'転職';return `<article class="phase8-job-row ${current?'current':''} ${unlocked?'':'locked'}" data-job-row="${job.id}"><div class="phase8-job-main"><div class="phase8-job-title"><span>${job.name}</span>${masteredJob?'<b>★MASTER</b>':''}</div><div class="phase8-job-meta"><span>${TIER_LABELS[job.tier]}</span><span>${unlocked?`Lv.${prog.level}`:'???'}</span>${parents.length?`<span>${parents.join(' × ')}</span>`:''}</div></div><div class="phase8-job-actions"><button class="inline-btn" data-job-detail="${job.id}">詳細</button><button class="job-card-btn" data-job-switch="${job.id}" ${current||!unlocked||blocked?'disabled':''}>${action}</button></div><div class="phase8-job-detail hidden" data-detail-for="${job.id}"><p>${unlocked?(job.desc||'固有説明なし'):`解放条件：${unlockRequirementText(job.id)}`}</p>${job.weapon&&WEAPON_TYPES[job.weapon]?`<p>得意武器：${WEAPON_TYPES[job.weapon].name}</p>`:''}${tierInfo?.masteryLv?`<p>MASTER Lv.${tierInfo.masteryLv}</p>`:''}${job.fusion?.fusionTrait?`<p><strong>Fusion Trait</strong>：${job.fusion.fusionTrait.summary}</p>`:''}${job.fusion?.resourceInteraction?`<p><strong>Resource</strong>：${job.fusion.resourceInteraction.summary}</p>`:''}</div></article>`;}

function bind(container){for(const b of container.querySelectorAll('[data-job-view]'))b.addEventListener('click',()=>{jobView=b.dataset.jobView;Audio_.tap();renderJobs();});const search=container.querySelector('.phase8-job-search');if(search)search.addEventListener('input',()=>{query=search.value;renderList(container);});for(const b of container.querySelectorAll('[data-tier]'))b.addEventListener('click',()=>{tierFilter=b.dataset.tier;Audio_.tap();renderList(container);});for(const b of container.querySelectorAll('[data-status]'))b.addEventListener('click',()=>{statusFilter=b.dataset.status;Audio_.tap();renderList(container);});for(const b of container.querySelectorAll('[data-job-detail]'))b.addEventListener('click',()=>{const d=container.querySelector(`[data-detail-for="${b.dataset.jobDetail}"]`);d?.classList.toggle('hidden');});for(const b of container.querySelectorAll('[data-job-switch]:not([disabled])'))b.addEventListener('click',()=>{const r=state.changeJob(b.dataset.jobSwitch);if(r.ok){Audio_.jobMastered();renderList(container);}});}

function renderList(container){const mastered=state.masteredSet(),all=['basic','advanced','special','hero'].flatMap(t=>jobsByTier(t));const filtered=all.filter(j=>matches(j,mastered));container.innerHTML=tabs()+toolbar(all,mastered)+`<div class="phase8-job-result-head"><strong>${filtered.length}件</strong><span>詳細は必要な職だけ展開</span></div><div class="phase8-job-list">${filtered.map(j=>compactCard(j,mastered)).join('')||'<div class="hint">条件に合う職業がありません。</div>'}</div>`;bind(container);}

export function renderJobs(){const container=document.getElementById('jobTiers');container.innerHTML=tabs();if(jobView==='constellation'){const host=document.createElement('div');host.className='job-constellation-host';container.appendChild(host);renderJobConstellation(host);bind(container);return;}renderList(container);}
