/* Battle 2.0 roadmap completion: Break, combos, companion tactics */
import { BattleEngine } from '../battleEngine.js';
import { TextBattleScreen } from '../screens/textBattle.js';
import { BREAK_RULES,COMPANION_TACTICS,breakCapacity,breakDamage,comboForHit,tickCombatStatuses } from '../data/battle2Tactics.js';
const proto=BattleEngine.prototype;
const originalSpawn=proto._spawnEnemy;
proto._spawnEnemy=function(type){const e=originalSpawn.call(this,type);e.breakMax=breakCapacity(e);e.breakGauge=e.breakMax;e.combat2BrokenTurns=0;e.combat2Statuses={burn:0,frost:0,wet:0,poison:0,bleed:0};return e;};
const originalCalc=proto.calculateDamage;
proto.calculateDamage=function(atk,target,opts={}){let result=originalCalc.call(this,atk,target,opts);if(!target||!result)return result;const element=result.element||opts.element||this._combat2ActiveElement||null;if(target.combat2BrokenTurns>0)result={...result,damage:Math.max(1,Math.round(result.damage*BREAK_RULES.brokenDamageMult))};this._battle2LastHit={targetId:target.id,damage:result.damage,element,elementMultiplier:result.elementMultiplier||1};return result;};
function applyCombo(engine,target,meta){const s=target.combat2Statuses||(target.combat2Statuses={burn:0,frost:0,wet:0,poison:0,bleed:0});const combo=comboForHit(meta.element,s);if(meta.element==='fire')s.burn=Math.max(s.burn,2);if(meta.element==='ice')s.frost=Math.max(s.frost,2);if(meta.element==='poison')s.poison=Math.max(s.poison,3);if(meta.element==='bleed')s.bleed=Math.max(s.bleed,3);if(combo==='wildfire'){s.burn=Math.max(s.burn,3);target.vulnerable={pct:Math.max(target.vulnerable?.pct||0,.12),turnsLeft:2};}else if(combo==='shock'){target.frozenTurns=Math.max(target.frozenTurns||0,1);s.frost=0;s.wet=0;}else if(combo==='necrosis'){target.vulnerable={pct:Math.max(target.vulnerable?.pct||0,.18),turnsLeft:2};}else if(combo==='shatter'){s.frost=0;target.vulnerable={pct:Math.max(target.vulnerable?.pct||0,.10),turnsLeft:1};}return combo;}
const originalApply=proto._applyDamageToEnemy;
proto._applyDamageToEnemy=function(target,damage,...rest){const before=target?.hp||0;const out=originalApply.call(this,target,damage,...rest);const meta=this._battle2LastHit?.targetId===target?.id?this._battle2LastHit:{targetId:target?.id,damage:Math.max(0,before-(target?.hp||0)),element:null,elementMultiplier:1};this._battle2LastHit=null;if(!target||target.dead)return out;target.breakMax ||= breakCapacity(target);target.breakGauge ??= target.breakMax;target.combat2Statuses ||= {burn:0,frost:0,wet:0,poison:0,bleed:0};const wasFrosted=target.combat2Statuses.frost>0;const combo=applyCombo(this,target,meta);const amount=breakDamage({damage:meta.damage,maxHp:target.maxHp,capacity:target.breakMax,elementMultiplier:meta.elementMultiplier,boss:!!target.boss,physical:!meta.element,frosted:wasFrosted,combo});target.breakGauge=Math.max(0,target.breakGauge-amount);const newlyBroken=target.breakGauge<=0&&target.combat2BrokenTurns<=0;if(newlyBroken){target.combat2BrokenTurns=1;if(target.pendingSpecial)target.pendingSpecial=null;}if(out&&combo)out.battle2Combo=combo;if(out){out.breakDamage=amount;if(newlyBroken)out.breakTriggered=true;}return out;};
const originalEnemyTurn=proto.performEnemyTurn;
proto.performEnemyTurn=function(enemy){if(enemy?.combat2BrokenTurns>0){enemy.combat2BrokenTurns--;const r={enemyId:enemy.id,name:enemy.name,kind:'stunned',break:true};if(enemy.combat2BrokenTurns<=0)enemy.breakGauge=enemy.breakMax||breakCapacity(enemy);return r;}const r=originalEnemyTurn.call(this,enemy);if(enemy?.combat2Statuses)enemy.combat2Statuses=tickCombatStatuses(enemy.combat2Statuses);return r;};
proto.battle2BreakInfo=function(enemy){return enemy?{current:Math.max(0,enemy.breakGauge??0),max:Math.max(1,enemy.breakMax||breakCapacity(enemy)),broken:(enemy.combat2BrokenTurns||0)>0}:null;};
proto.setCompanionTactic=function(id){if(!COMPANION_TACTICS[id])return false;this.companionTactic=id;for(const c of this.companions||[]){c._battle2OriginalNature ||= c.nature;const override=COMPANION_TACTICS[id].nature;c.nature=override||c._battle2OriginalNature;}return true;};
const originalAdvance=proto.advanceTurn;
proto.advanceTurn=function(command){if(!this.companionTactic)this.companionTactic='balanced';this.setCompanionTactic(this.companionTactic);return originalAdvance.call(this,command);};
const originalRender=TextBattleScreen.prototype._render;
TextBattleScreen.prototype._render=function(){originalRender.call(this);if(!this.engine)return;for(const card of this.el.enemyList?.querySelectorAll('.tb-enemy-card')||[]){const idx=[...this.el.enemyList.children].indexOf(card),e=this.engine.enemies[idx];if(!e||e.dead)continue;let line=card.querySelector('.tb-break-line');if(!line){line=document.createElement('div');line.className='tb-break-line';line.style.cssText='font-size:11px;opacity:.8;margin-top:3px';card.appendChild(line);}const info=this.engine.battle2BreakInfo(e);const pct=Math.max(0,Math.round(info.current/info.max*100));line.textContent=`BREAK ${pct}%${info.broken?' — BURST WINDOW':''}`;}let hud=document.getElementById('tbBattle2Tactics');const parent=document.getElementById('tbCompanionHud');if(parent&&this.engine.companions?.length){if(!hud){hud=document.createElement('div');hud.id='tbBattle2Tactics';hud.style.cssText='margin-top:5px;display:flex;gap:4px;flex-wrap:wrap';parent.appendChild(hud);}hud.innerHTML=Object.values(COMPANION_TACTICS).map(t=>`<button class="btn-sub" data-tactic="${t.id}" style="padding:3px 6px;font-size:11px" ${this.engine.companionTactic===t.id?'disabled':''}>${t.name}</button>`).join('');hud.querySelectorAll('[data-tactic]').forEach(b=>b.addEventListener('click',()=>{this.engine.setCompanionTactic(b.dataset.tactic);this._render();}));}};
export { COMPANION_TACTICS };
