/* Content Pack IV D — first visible Branch anchor handoff runtime. */
import './contentPackIVE.js';
import { syncCP4IdentityReward } from './contentPackIVF.js';
import { state } from '../state.js';
import { CP4_FIRST_BRANCH_ANCHOR,cp4FirstBranchAnchorProgress } from '../data/contentPackIVD.js';
function world(){state.data.world2??={};state.data.world2.discoveries??={};return state.data.world2;}
function put(id,patch){const d=world().discoveries,prev=d[id]||{};d[id]={...prev,...patch,at:prev.at||Date.now()};return d[id];}
export function cp4FirstBranchAnchor(){const discoveries=world().discoveries;const progress=cp4FirstBranchAnchorProgress({discoveries});return{anchor:CP4_FIRST_BRANCH_ANCHOR,progress};}
export function observeCP4FirstBranchAnchor(){const{anchor,progress}=cp4FirstBranchAnchor();if(!progress.visible)return null;if(!progress.observed){put(anchor.discoveryId,{name:anchor.name,hint:anchor.observed,nextAction:anchor.next,contentPackIV:true,branchAnchor:true,observedBranchAnchor:true,sourceDiscoveryId:anchor.sourceEvidenceDiscoveryId,targetChapter:anchor.chapterNum,traversable:false,deepGreenAbsentHidden:true,totalBranchCountHidden:true});state.save();}syncCP4IdentityReward();return world().discoveries[anchor.discoveryId];}
state.cp4FirstBranchAnchor=()=>cp4FirstBranchAnchor();state.observeCP4FirstBranchAnchor=()=>observeCP4FirstBranchAnchor();
function renderAnchorCard(){if(typeof document==='undefined')return;const list=document.getElementById('stageList'),title=document.getElementById('chapterTitle');if(!list||!title)return;const existing=list.querySelector('[data-cp4-branch-anchor="tree-sovereign"]');const isDeepGreen=/第2章/.test(title.textContent||'');const{anchor,progress}=cp4FirstBranchAnchor();if(!isDeepGreen||!progress.visible){existing?.remove();return;}if(existing)return;const card=document.createElement('div');card.className='stage-card branch';card.dataset.cp4BranchAnchor='tree-sovereign';const name=progress.observed?anchor.name:anchor.hiddenLabel;const detail=progress.observed?`${anchor.observed} ${anchor.next}`:anchor.preview;card.innerHTML=`<div><div class="name">◈ ${name}</div><div class="rec">${detail}</div></div><div class="cleared">${progress.observed?'OBSERVED':'?'}</div>`;if(!progress.observed){const action=document.createElement('button');action.className='btn-sub';action.textContent='重なりを観測';action.addEventListener('click',ev=>{ev.stopPropagation();observeCP4FirstBranchAnchor();card.remove();renderAnchorCard();});card.firstElementChild.appendChild(action);}list.appendChild(card);}
if(typeof MutationObserver!=='undefined'&&typeof document!=='undefined'){const start=()=>{const root=document.getElementById('stageList');if(!root)return;new MutationObserver(()=>renderAnchorCard()).observe(root,{childList:true});renderAnchorCard();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();}
