/* ============================================================
   Progression 2.0 Phase 4 — Inheritance Core
   ============================================================ */
import { state } from '../state.js';
import { CHARACTER_LAYER } from '../data/balance.js';
import { INHERITABLE_STAT_KEYS, INHERITANCE_MIN_LEVEL, inheritanceRatePct, inheritanceBonusPointGain, calculateInheritedStats } from '../data/inheritance.js';
function emptyStats(){return Object.fromEntries(INHERITABLE_STAT_KEYS.map(key=>[key,0]));}
function normalizeStats(value){const out=emptyStats();for(const key of INHERITABLE_STAT_KEYS)out[key]=Math.max(0,Math.floor(Number(value?.[key])||0));return out;}
function ensureInheritanceData(){if(!Number.isFinite(state.data.reincarnations))state.data.reincarnations=0;state.data.reincarnations=Math.max(0,Math.floor(state.data.reincarnations));state.data.inheritedStats=normalizeStats(state.data.inheritedStats);state.data.inheritanceAllocated=normalizeStats(state.data.inheritanceAllocated);if(!Number.isFinite(state.data.inheritanceBonusPoints))state.data.inheritanceBonusPoints=0;state.data.inheritanceBonusPoints=Math.max(0,Math.floor(state.data.inheritanceBonusPoints));if(!Array.isArray(state.data.inheritanceHistory))state.data.inheritanceHistory=[];}
function withLegacyRebirthDisabled(fn){const previous=state.data.reincarnations;state.data.reincarnations=0;try{return fn();}finally{state.data.reincarnations=previous;}}
function characterIntrinsicAtLevel(level){const lv=Math.max(1,Math.floor(Number(level)||1)),out=emptyStats();for(const key of INHERITABLE_STAT_KEYS){const base=Number(CHARACTER_LAYER.STAT_BASE[key])||0,growth=Number(CHARACTER_LAYER.STAT_GROWTH[key])||0;out[key]=Math.max(0,Math.floor(base+growth*(lv-1)));}return out;}
ensureInheritanceData();
state.inheritanceMinLevel=INHERITANCE_MIN_LEVEL;
state.canPerformInheritance=function(){return Math.max(1,Math.floor(Number(this.characterLevel)||1))>=INHERITANCE_MIN_LEVEL;};
state.inheritanceRatePct=function(level=this.characterLevel,count=this.data.reincarnations){return inheritanceRatePct(level,count);};
state.inheritanceBonusPointGain=function(level=this.characterLevel,count=this.data.reincarnations){return inheritanceBonusPointGain(level,count);};
state.inheritanceIntrinsicStats=function(){ensureInheritanceData();const levelGrowth=characterIntrinsicAtLevel(this.characterLevel),out=emptyStats();for(const key of INHERITABLE_STAT_KEYS)out[key]=Math.max(0,Math.floor((Number(levelGrowth[key])||0)+(Number(this.data.inheritedStats[key])||0)+(Number(this.data.inheritanceAllocated[key])||0)));return out;};
state.inheritancePreview=function(){ensureInheritanceData();const level=this.characterLevel,count=this.data.reincarnations,ratePct=inheritanceRatePct(level,count),bonusPoints=inheritanceBonusPointGain(level,count),sourceStats=this.inheritanceIntrinsicStats(),nextInheritedStats=calculateInheritedStats(sourceStats,level,count);return{level,count,ratePct,bonusPoints,sourceStats,nextInheritedStats,canPerform:this.canPerformInheritance(),minLevel:INHERITANCE_MIN_LEVEL};};
state.performInheritance=function(){ensureInheritanceData();if(!this.canPerformInheritance())return false;const preview=this.inheritancePreview();this.data.inheritedStats=normalizeStats(preview.nextInheritedStats);this.data.inheritanceBonusPoints+=preview.bonusPoints;this.data.reincarnations+=1;this.data.characterLevel=1;this.data.characterExp=0;this.data.inheritanceHistory.push({at:Date.now(),fromLevel:preview.level,ratePct:preview.ratePct,bonusPoints:preview.bonusPoints,inheritedStats:normalizeStats(preview.nextInheritedStats)});if(this.data.inheritanceHistory.length>50)this.data.inheritanceHistory.shift();this.save();return preview;};
state.reincarnationCost=function(){return{gold:0,manastone:0};};
state.reincarnate=function(){return !!this.performInheritance();};
state.inheritanceUnspentPoints=function(){ensureInheritanceData();const spent=INHERITABLE_STAT_KEYS.reduce((sum,key)=>sum+(Number(this.data.inheritanceAllocated[key])||0),0);return Math.max(0,this.data.inheritanceBonusPoints-spent);};
state.allocateInheritancePoints=function(stat,amount=1){ensureInheritanceData();if(!INHERITABLE_STAT_KEYS.includes(stat))return 0;const requested=Math.max(0,Math.floor(Number(amount)||0)),used=Math.min(requested,this.inheritanceUnspentPoints());if(used<=0)return 0;this.data.inheritanceAllocated[stat]+=used;this.save();return used;};
state.resetInheritanceAllocation=function(){ensureInheritanceData();this.data.inheritanceAllocated=emptyStats();this.save();return true;};
const phase3GetStats=state.getStats.bind(state),phase3GetStatBreakdown=state.getStatBreakdown.bind(state);
state.getStats=function(){ensureInheritanceData();const base=withLegacyRebirthDisabled(()=>phase3GetStats()),out={...base};for(const key of INHERITABLE_STAT_KEYS){const add=(Number(this.data.inheritedStats[key])||0)+(Number(this.data.inheritanceAllocated[key])||0);if(key==='spd')out[key]=Math.round(((Number(out[key])||0)+add)*10)/10;else out[key]=Math.round((Number(out[key])||0)+add);}return out;};
state.getStatBreakdown=function(stat){ensureInheritanceData();const legacy=withLegacyRebirthDisabled(()=>phase3GetStatBreakdown(stat)),inheritance=INHERITABLE_STAT_KEYS.includes(stat)?(Number(this.data.inheritedStats[stat])||0)+(Number(this.data.inheritanceAllocated[stat])||0):0,total=Number(this.getStats()?.[stat]??legacy.total??0),values={characterJobBase:Number(legacy.characterJobBase??legacy.base??0),inheritance,equipment:Number(legacy.equipment||0),permanent:Number(legacy.permanent||0),affix:Number(legacy.affix||0),codex:Number(legacy.codex||0),rune:Number(legacy.rune||0)},accounted=Object.values(values).reduce((sum,v)=>sum+v,0),special=Math.round((total-accounted)*10)/10;return{...legacy,...values,base:values.characterJobBase,inheritance,special,total};};
export { INHERITABLE_STAT_KEYS, INHERITANCE_MIN_LEVEL, ensureInheritanceData, withLegacyRebirthDisabled, characterIntrinsicAtLevel };
