import { state } from '../state.js';
import { getCompanionSpecies } from '../data/companions.js';
import { godRollProfile,memoryValue,ranchCapacity,researchLevel,researchUnlocked } from '../data/monsterRanch.js';
import { SPECIES_BOARD_NODES,speciesBoardNode,speciesBoardCost,speciesBoardEffects } from '../data/monsterRanchBoard.js';

function ensure(){let changed=false;if(!state.data.ranchResearch){state.data.ranchResearch={};changed=true;}if(!state.data.ranchMemory){state.data.ranchMemory={};changed=true;}if(!state.data.ranchSpeciesBoard){state.data.ranchSpeciesBoard={};changed=true;}for(const inst of Object.values(state.data.companionInstances||{}))if(inst.favorite==null){inst.favorite=false;changed=true;}if(changed)state.save();}
ensure();
state.ranchCapacity=function(){return ranchCapacity(this.settlementLevel?.('ranch')||0);};
state.ranchCount=function(){return Object.keys(this.data.companionInstances||{}).length;};
state.ranchHasSpace=function(){return this.ranchCount()<this.ranchCapacity();};
state.ranchResearch=function(speciesId){ensure();const r=this.data.ranchResearch[speciesId]||{recruited:0,released:0};return{...r,level:researchLevel(r.recruited),mastered:researchUnlocked(r.recruited,'mastered')};};
state.recordRanchRecruit=function(speciesId){ensure();const r=this.data.ranchResearch[speciesId]||(this.data.ranchResearch[speciesId]={recruited:0,released:0});r.recruited++;this.save();return this.ranchResearch(speciesId);};
state.ranchMemory=function(speciesId){ensure();return Math.max(0,Math.floor(this.data.ranchMemory[speciesId]||0));};
state.ranchBoardRanks=function(speciesId){ensure();return{...(this.data.ranchSpeciesBoard[speciesId]||{})};};
state.ranchBoardEffects=function(speciesId){return speciesBoardEffects(this.ranchBoardRanks(speciesId));};
state.canBuyRanchBoardNode=function(speciesId,nodeId){ensure();const species=getCompanionSpecies(speciesId),node=speciesBoardNode(nodeId);if(!species||!node)return{ok:false,reason:'unknown'};const research=this.ranchResearch(speciesId);if(research.recruited<node.requiresResearch)return{ok:false,reason:'research',required:node.requiresResearch};const ranks=this.ranchBoardRanks(speciesId),rank=Math.max(0,Math.floor(ranks[nodeId]||0));if(rank>=node.maxRank)return{ok:false,reason:'max'};const cost=speciesBoardCost(node,rank);if(this.ranchMemory(speciesId)<cost)return{ok:false,reason:'memory',cost};return{ok:true,cost,rank,nextRank:rank+1};};
state.buyRanchBoardNode=function(speciesId,nodeId){const check=this.canBuyRanchBoardNode(speciesId,nodeId);if(!check.ok)return check;this.data.ranchMemory[speciesId]-=check.cost;const ranks=this.data.ranchSpeciesBoard[speciesId]||(this.data.ranchSpeciesBoard[speciesId]={});ranks[nodeId]=check.nextRank;this.save();return{ok:true,cost:check.cost,rank:check.nextRank,effects:this.ranchBoardEffects(speciesId)};};
state.ranchSpeciesBoardNodes=SPECIES_BOARD_NODES;
state.toggleCompanionFavorite=function(instanceId){ensure();const inst=this.data.companionInstances?.[instanceId];if(!inst)return false;inst.favorite=!inst.favorite;this.save();return inst.favorite;};
state.ranchReleaseCompanion=function(instanceId){ensure();const inst=this.data.companionInstances?.[instanceId];if(!inst||inst.favorite)return{ok:false,reason:inst?.favorite?'favorite':'missing'};const speciesId=inst.speciesId,value=memoryValue(inst);if(!this.releaseCompanion(instanceId))return{ok:false,reason:'release'};this.data.ranchMemory[speciesId]=(this.data.ranchMemory[speciesId]||0)+value;const r=this.data.ranchResearch[speciesId]||(this.data.ranchResearch[speciesId]={recruited:0,released:0});r.released++;this.save();return{ok:true,speciesId,memory:value,total:this.ranchMemory(speciesId)};};
state.ranchCompanionInfo=function(instanceId){const c=this.getCompanion?.(instanceId);if(!c)return null;return{...c,godRoll:godRollProfile(c.instance),research:this.ranchResearch(c.species.id),memory:this.ranchMemory(c.species.id),board:this.ranchBoardRanks(c.species.id),boardEffects:this.ranchBoardEffects(c.species.id)};};
state.ranchSpeciesSummary=function(speciesId){const species=getCompanionSpecies(speciesId);if(!species)return null;const owned=Object.entries(this.data.companionInstances||{}).filter(([,x])=>x.speciesId===speciesId).map(([id])=>this.ranchCompanionInfo(id)).filter(Boolean);owned.sort((a,b)=>(b.godRoll.score-a.godRoll.score)||b.instance.level-a.instance.level);return{species,research:this.ranchResearch(speciesId),memory:this.ranchMemory(speciesId),board:this.ranchBoardRanks(speciesId),boardEffects:this.ranchBoardEffects(speciesId),owned,best:owned[0]||null};};
