import { state } from '../state.js';
import { COMPANION_NATURES, COMPANION_RARITY, COMPANION_RARITY_LABEL, companionTraitLabel } from '../data/companions.js';
import { RANCH_RESEARCH_MILESTONES } from '../data/monsterRanch.js';

const STATS=['hp','mp','atk','def','mag','spd'];
const LABEL={hp:'HP',mp:'MP',atk:'ATK',def:'DEF',mag:'MAG',spd:'SPD'};
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
function stars(r){return'★'.repeat(Math.max(1,COMPANION_RARITY.indexOf(r)+1));}
function renderResearch(speciesId){const r=state.ranchResearch(speciesId),next=RANCH_RESEARCH_MILESTONES.find(m=>r.recruited<m.count);return `<div class="forge-card-sub">研究 Lv.${r.level} / 加入 ${r.recruited} / 帰還 ${r.released}${r.mastered?' / <strong>MASTERED</strong>':next?` / 次: ${next.count}体 → ${next.label}`:''}</div><div class="forge-card-sub">種族の記憶 ${state.ranchMemory(speciesId)}</div>`;}
function renderCard(info){const {id,species,instance,godRoll}=info,nature=COMPANION_NATURES[instance.nature]||COMPANION_NATURES.balanced,slot=state.data.companionParty.indexOf(id),traits=(species.traits||[]).map(companionTraitLabel).join('・')||'なし';const talents=STATS.map(k=>`${LABEL[k]} <strong>${godRoll.grades[k]||'B'}</strong>`).join('　');return `<div class="forge-card ranch-card" data-id="${esc(id)}"><div class="forge-card-top"><div class="forge-card-name">${instance.favorite?'★ ':''}${species.icon||'🐾'} ${esc(instance.nickname||species.name)} ${godRoll.isGodRoll?'<span class="mastered-badge">✦ GOD ROLL</span>':''}</div><strong>${stars(instance.rarity)}</strong></div><div class="forge-card-sub">Lv.${instance.level} / ${COMPANION_RARITY_LABEL[instance.rarity]} / 性格: ${esc(nature.name)}${slot>=0?` / 編成${slot+1}`:''}</div><div class="forge-card-sub">出身: ${esc(species.regionName||instance.origin||'不明')}</div><div class="forge-card-sub">Talent: ${talents}${godRoll.profile?` / ${godRoll.profile}型`:''}</div><div class="forge-card-sub">Trait: ${esc(traits)}</div>${renderResearch(species.id)}<div class="confirm-actions" style="margin-top:8px;"><button class="btn-sub ranch-fav" data-id="${esc(id)}">${instance.favorite?'★ お気に入り解除':'☆ お気に入り'}</button>${[0,1,2].map(i=>`<button class="btn-sub ranch-slot" data-id="${esc(id)}" data-slot="${i}" ${slot===i?'disabled':''}>${slot===i?`編成${i+1}`:`枠${i+1}`}</button>`).join('')}<button class="btn-sub ranch-release" data-id="${esc(id)}" ${instance.favorite?'disabled':''}>野へ帰す</button></div></div>`;}
export function renderMonsterRanch(){const content=document.getElementById('companionContent');if(!content||!state.ranchCompanionInfo)return;const list=state.companionList().map(c=>state.ranchCompanionInfo(c.id)).filter(Boolean).sort((a,b)=>Number(b.instance.favorite)-Number(a.instance.favorite)||(b.godRoll.score-a.godRoll.score)||b.instance.level-a.instance.level);const cap=state.ranchCapacity(),count=state.ranchCount();content.innerHTML=`<div class="forge-card"><div class="forge-card-top"><div class="forge-card-name">モンスター牧場</div><strong>${count}/${cap}</strong></div><div class="forge-card-sub">同じ種族を集めるほど研究が進む。優秀な個体はお気に入りで保護し、不要な個体は野へ帰すと「種族の記憶」を残す。</div><div class="forge-card-sub">牧舎Lv.${state.settlementLevel?.('ranch')||0}　／　登録種 ${Object.keys(state.data.ranchResearch||{}).length}</div></div>${list.length?list.map(renderCard).join(''):'<p class="hint">まだ牧場にモンスターはいません。</p>'}`;content.querySelectorAll('.ranch-fav').forEach(b=>b.addEventListener('click',()=>{state.toggleCompanionFavorite(b.dataset.id);renderMonsterRanch();}));content.querySelectorAll('.ranch-slot').forEach(b=>b.addEventListener('click',()=>{state.setCompanionSlot(Number(b.dataset.slot),b.dataset.id);renderMonsterRanch();}));content.querySelectorAll('.ranch-release').forEach(b=>b.addEventListener('click',()=>{const c=state.getCompanion(b.dataset.id);if(!c||c.instance.favorite)return;const name=c.instance.nickname||c.species.name;if(!window.confirm(`${name}を野へ帰しますか？\n種族の記憶を残します。`))return;state.ranchReleaseCompanion(b.dataset.id);renderMonsterRanch();}));}
function install(){const btn=document.getElementById('goCompanionBtn');if(btn){const label=[...btn.querySelectorAll('span')].at(-1);if(label)label.textContent='モンスター牧場';btn.addEventListener('click',()=>{const h=document.querySelector('#companionScreen h2');if(h)h.textContent='モンスター牧場';queueMicrotask(renderMonsterRanch);});}const back=document.getElementById('companionBackBtn');if(back)back.addEventListener('click',()=>{const h=document.querySelector('#companionScreen h2');if(h)h.textContent='モンスター牧場';});}
install();
