/* Monster Ranch 2.0 — wild eggs, directed training, expeditions and research unlocks */
import { state } from '../state.js';
import { TextBattleScreen } from '../screens/textBattle.js';
import { getCompanionSpecies } from '../data/companions.js';

const EXPEDITIONS=Object.freeze({
 meadow:{id:'meadow',name:'草原調査',minLv:1,duration:10*60*1000,reward:{wood:12,hide:8},eggChance:.12},
 ruins:{id:'ruins',name:'遺跡探索',minLv:2,duration:30*60*1000,reward:{ore:18,wood:8},eggChance:.20},
 abyss:{id:'abyss',name:'深淵遠征',minLv:4,duration:60*60*1000,reward:{ore:24,hide:18,veilstone:2},eggChance:.32},
});
function ensure(){let changed=false;if(!Array.isArray(state.data.ranchExpeditions)){state.data.ranchExpeditions=[];changed=true;}if(!state.data.ranchResearchDiscoveries){state.data.ranchResearchDiscoveries={};changed=true;}if(changed)state.save();}
ensure();
state.ranchExpeditionDefs=EXPEDITIONS;
state.ranchResearchUnlocks=function(){const lv=this.ranchFacilityLevel?.('research')||0;return{wildEggs:lv>=1,traitAnalysis:lv>=2,directedInheritance:lv>=3,mutationHints:lv>=4,masterArchive:lv>=5};};
state.trainRanchCompanion=function(instanceId,focus='balanced'){if((this.ranchFacilityLevel?.('training')||0)<1)return{ok:false,reason:'training'};const inst=this.data.companionInstances?.[instanceId];if(!inst)return{ok:false,reason:'missing'};const cost=120+Math.max(1,inst.level||1)*8;if((this.data.gold||0)<cost)return{ok:false,reason:'gold',cost};this.data.gold-=cost;const exp=Math.round((28+Math.max(1,inst.level||1)*5)*(this.ranchFacilityEffects?.().companionExpMult||1));this.gainCompanionExp?.(instanceId,exp);this.gainCompanionBond?.(instanceId,2,{battle:false});inst.trainingFocus=focus;inst.trainingSessions=(inst.trainingSessions||0)+1;const stat=focus==='power'?'atk':focus==='guard'?'def':focus==='magic'?'mag':focus==='speed'?'spd':null;if(stat){inst.trainingBonus ||= {};inst.trainingBonus[stat]=Math.min(.10,(inst.trainingBonus[stat]||0)+.002);}this.save();return{ok:true,exp,cost,focus,sessions:inst.trainingSessions};};
state.startRanchExpedition=function(instanceIds,expeditionId){ensure();const def=EXPEDITIONS[expeditionId],ids=[...new Set(instanceIds||[])].filter(Boolean);if(!def||ids.length<1||ids.length>3)return{ok:false,reason:'party'};if((this.ranchFacilityLevel?.('research')||0)<def.minLv)return{ok:false,reason:'research',required:def.minLv};if(ids.some(id=>!this.data.companionInstances?.[id]))return{ok:false,reason:'missing'};const busy=new Set(this.data.ranchExpeditions.filter(x=>!x.claimed).flatMap(x=>x.instanceIds));if(ids.some(id=>busy.has(id)))return{ok:false,reason:'busy'};const id=`rex_${Date.now()}_${Math.floor(Math.random()*10000)}`;this.data.ranchExpeditions.push({id,expeditionId,instanceIds:ids,startedAt:Date.now(),endsAt:Date.now()+def.duration,claimed:false});this.save();return{ok:true,id,endsAt:Date.now()+def.duration};};
state.ranchExpeditionList=function(){ensure();const now=Date.now();return this.data.ranchExpeditions.filter(x=>!x.claimed).map(x=>({...x,ready:now>=x.endsAt,def:EXPEDITIONS[x.expeditionId]}));};
state.claimRanchExpedition=function(id,rng=Math.random){ensure();const run=this.data.ranchExpeditions.find(x=>x.id===id&&!x.claimed),now=Date.now();if(!run)return{ok:false,reason:'missing'};if(now<run.endsAt)return{ok:false,reason:'time',remaining:run.endsAt-now};const def=EXPEDITIONS[run.expeditionId];this.data.settlementMaterials ||= {};for(const[k,v]of Object.entries(def.reward))this.data.settlementMaterials[k]=(this.data.settlementMaterials[k]||0)+v;for(const cid of run.instanceIds){this.gainCompanionExp?.(cid,45*def.minLv);this.gainCompanionBond?.(cid,3+def.minLv,{battle:false});}let eggId=null;if(rng()<def.eggChance){const candidates=run.instanceIds.map(cid=>this.data.companionInstances[cid]?.speciesId).filter(Boolean);const speciesId=candidates[Math.floor(rng()*candidates.length)];if(speciesId)eggId=this.createRanchEgg?.(speciesId,{origin:'expedition',rarity:def.minLv>=4?'rare':null});}run.claimed=true;this.save();return{ok:true,reward:{...def.reward},eggId};};
state.rollWildRanchEgg=function({speciesId=null,elite=false,boss=false,abyss=false}={},rng=Math.random){if(!(this.ranchResearchUnlocks?.().wildEggs))return null;let chance=.012+(elite?.018:0)+(boss?.025:0)+(abyss?.02:0);chance+=.004*Math.max(0,(this.ranchFacilityLevel?.('research')||1)-1);if(rng()>=chance)return null;let sid=speciesId;if(!sid){const owned=Object.values(this.data.companionInstances||{}).map(x=>x.speciesId).filter(x=>getCompanionSpecies(x));sid=owned.length?owned[Math.floor(rng()*owned.length)]:'slime';}return this.createRanchEgg?.(sid,{origin:abyss?'abyssWildEgg':'wildEgg',rarity:(elite||boss)?'rare':null});};
// One post-battle seam: wild eggs are rolled once per cleared battle, never per kill.
const previousStart=TextBattleScreen.prototype.start;TextBattleScreen.prototype.start=function(stageId,onEnd,blessingId){return previousStart.call(this,stageId,result=>{if(result?.cleared){const candidate=result.recruitCandidate;result.ranchEggDrop=state.rollWildRanchEgg?.({speciesId:candidate?.speciesId||null,elite:!!candidate?.elite,boss:!!this.engine?.stage?.boss,isAbyss:!!this.engine?.stage?.isAbyss,abyss:!!this.engine?.stage?.isAbyss})||null;}onEnd(result);},blessingId);};
