/* Monster Ranch 2.0 — facility progression, eggs and breeding eggs */
import { state } from '../state.js';
import { RANCH_FACILITIES,ranchFacility,ranchFacilityCost,ranchFacilityEffects } from '../data/monsterRanchFacilities.js';
import { BREEDING_COST,breedingSpecies,inheritTalent,inheritNature,inheritRarity,inheritTraits } from '../data/companionBreeding.js';

function ensure(){let changed=false;if(!state.data.ranchFacilities){state.data.ranchFacilities={};changed=true;}for(const f of RANCH_FACILITIES)if(!Number.isFinite(state.data.ranchFacilities[f.id])){state.data.ranchFacilities[f.id]=0;changed=true;}if(!Array.isArray(state.data.ranchEggs)){state.data.ranchEggs=[];changed=true;}if(!Number.isFinite(state.data.nextRanchEggSeq)){state.data.nextRanchEggSeq=1;changed=true;}if(changed)state.save();}
ensure();
state.ranchFacilities=RANCH_FACILITIES;
state.ranchFacilityLevel=function(id){ensure();return Math.max(0,Math.floor(this.data.ranchFacilities[id]||0));};
state.ranchFacilityEffects=function(){ensure();return ranchFacilityEffects(this.data.ranchFacilities);};
state.canUpgradeRanchFacility=function(id){ensure();const f=ranchFacility(id);if(!f)return{ok:false,reason:'unknown'};const lv=this.ranchFacilityLevel(id);if(lv>=f.maxLevel)return{ok:false,reason:'max'};const next=lv+1,ranchLv=this.settlementLevel?.('ranch')||0;if(next>ranchLv)return{ok:false,reason:'ranch',required:next};const cost=ranchFacilityCost(id,next),materials=this.data.settlementMaterials||{};for(const[k,v]of Object.entries(cost))if((materials[k]||0)<v)return{ok:false,reason:'materials',cost};return{ok:true,next,cost};};
state.upgradeRanchFacility=function(id){const check=this.canUpgradeRanchFacility(id);if(!check.ok)return check;for(const[k,v]of Object.entries(check.cost))this.data.settlementMaterials[k]-=v;this.data.ranchFacilities[id]=check.next;this.save();return{ok:true,level:check.next,effects:this.ranchFacilityEffects()};};
state.createRanchEgg=function(speciesId,opts={}){ensure();if(!speciesId)return null;const id=`egg_${this.data.nextRanchEggSeq++}`;this.data.ranchEggs.push({id,speciesId,rarity:opts.rarity||null,nature:opts.nature||null,talent:opts.talent?{...opts.talent}:null,inheritedTraits:[...(opts.inheritedTraits||[])],generation:Number(opts.generation)||0,parents:[...(opts.parents||[])],origin:opts.origin||'egg',createdAt:Date.now()});this.save();return id;};
state.ranchEggList=function(){ensure();return this.data.ranchEggs.map(x=>({...x,talent:x.talent?{...x.talent}:null,inheritedTraits:[...(x.inheritedTraits||[])],parents:[...(x.parents||[])]}));};
function applyIncubatorFloor(inst,bonus){if(!inst?.talent||bonus<=0)return;const floor=.94+bonus;for(const k of ['hp','mp','atk','def','mag','spd'])if((inst.talent[k]||0)<floor)inst.talent[k]=Math.round(floor*1000)/1000;}
state.hatchRanchEgg=function(eggId){ensure();if(this.ranchFacilityLevel('incubator')<1)return{ok:false,reason:'incubator'};if(!this.ranchHasSpace?.())return{ok:false,reason:'full'};const index=this.data.ranchEggs.findIndex(x=>x.id===eggId);if(index<0)return{ok:false,reason:'missing'};const egg=this.data.ranchEggs[index],opts={origin:egg.origin||'hatch'};if(egg.rarity)opts.rarity=egg.rarity;if(egg.nature)opts.nature=egg.nature;if(egg.talent)opts.talent={...egg.talent};const childId=this.createCompanion(egg.speciesId,opts),inst=this.data.companionInstances[childId];if(!inst)return{ok:false,reason:'create'};inst.generation=egg.generation||0;inst.parents=[...(egg.parents||[])];inst.inheritedTraits=[...(egg.inheritedTraits||[])];inst.hatchedAt=Date.now();applyIncubatorFloor(inst,this.ranchFacilityEffects().talentFloorBonus);this.data.ranchEggs.splice(index,1);this.recordRanchRecruit?.(egg.speciesId);this.save();return{ok:true,childId,child:this.getCompanion?.(childId)};};
state.canCreateBreedingEgg=function(aId,bId){ensure();if(this.ranchFacilityLevel('incubator')<1)return{ok:false,reason:'incubator'};if(!aId||!bId||aId===bId)return{ok:false,reason:'parents'};const a=this.getCompanion?.(aId),b=this.getCompanion?.(bId);if(!a||!b)return{ok:false,reason:'missing'};if(this.data.gold<BREEDING_COST.gold||this.data.manastone<BREEDING_COST.manastone)return{ok:false,reason:'cost'};return{ok:true,a,b};};
state.createBreedingEgg=function(aId,bId,rng=Math.random){const probe=this.canCreateBreedingEgg(aId,bId);if(!probe.ok)return probe;const{a,b}=probe,speciesId=breedingSpecies(a.instance.baseSpeciesId||a.instance.speciesId,b.instance.baseSpeciesId||b.instance.speciesId,rng),generation=Math.max(Number(a.instance.generation)||0,Number(b.instance.generation)||0)+1,talent=inheritTalent(a.instance.talent,b.instance.talent,rng),nature=inheritNature(a.instance.nature,b.instance.nature,rng),rarity=inheritRarity(a.instance.rarity,b.instance.rarity,rng),inheritedTraits=inheritTraits(a,b,speciesId,rng);this.data.gold-=BREEDING_COST.gold;this.data.manastone-=BREEDING_COST.manastone;const eggId=this.createRanchEgg(speciesId,{rarity,nature,talent,inheritedTraits,generation,parents:[aId,bId],origin:'breedingEgg'});return{ok:true,eggId,speciesId,generation,inheritedTraits};};

// Facility bonuses reuse canonical progression seams and stay bounded.
if(state.gainPartyCompanionExp){const previous=state.gainPartyCompanionExp.bind(state);state.gainPartyCompanionExp=function(amount){return previous(amount*this.ranchFacilityEffects().companionExpMult);};}
if(state.gainCompanionBond){const previous=state.gainCompanionBond.bind(state);state.gainCompanionBond=function(id,amount,opts={}){return previous(id,amount*this.ranchFacilityEffects().bondExpMult,opts);};}
