/* Monster Ranch 2.0 — facility / incubation UI */
import { state } from '../state.js';
import { getCompanionSpecies,COMPANION_RARITY_LABEL } from '../data/companions.js';
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
function costText(cost={}){const names={wood:'古木',ore:'鉱石',hide:'魔獣皮',veilstone:'境界石'};return Object.entries(cost).filter(([,v])=>v>0).map(([k,v])=>`${names[k]||k} ${v}`).join(' / ');}
function facilityCards(){return(state.ranchFacilities||[]).map(f=>{const lv=state.ranchFacilityLevel(f.id),check=state.canUpgradeRanchFacility(f.id),cost=check.cost||f.costs?.[lv]||{},reason=check.reason==='ranch'?`牧舎Lv.${check.required}が必要`:check.reason==='materials'?'素材不足':check.reason==='max'?'MAX':'';return `<div class="forge-card" style="margin-top:6px"><div class="forge-card-top"><div class="forge-card-name">${esc(f.name)}</div><strong>Lv.${lv}/${f.maxLevel}</strong></div><div class="forge-card-sub">${esc(f.desc)}</div><button class="btn-sub ranch2-upgrade" data-id="${f.id}" ${check.ok?'':'disabled'}>${lv>=f.maxLevel?'MAX':`強化 — ${costText(cost)}`}${reason?` / ${reason}`:''}</button></div>`;}).join('');}
function eggCards(){const eggs=state.ranchEggList?.()||[];if(!eggs.length)return'<div class="forge-card-sub">卵はまだありません。</div>';return eggs.map(e=>{const s=getCompanionSpecies(e.speciesId),rarity=e.rarity?(COMPANION_RARITY_LABEL[e.rarity]||e.rarity):'孵化時抽選';return `<div class="forge-card" style="margin-top:6px"><div class="forge-card-top"><div class="forge-card-name">🥚 ${esc(s?.name||e.speciesId)}の卵</div><strong>${esc(rarity)}</strong></div><div class="forge-card-sub">${e.origin==='breedingEgg'?`配合卵 / 第${e.generation}世代`:'モンスターの卵'}${e.inheritedTraits?.length?` / 継承候補: ${esc(e.inheritedTraits.join('・'))}`:''}</div><button class="btn-highlight ranch2-hatch" data-id="${esc(e.id)}">孵化する</button></div>`;}).join('');}
function parentOptions(){return(state.companionList?.()||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.instance.nickname||c.species.name)} Lv.${c.instance.level}</option>`).join('');}
export function installRanch2Panel(){const root=document.getElementById('companionContent');if(!root||!state.ranchFacilityLevel)return;document.getElementById('monsterRanch2Panel')?.remove();const panel=document.createElement('div');panel.id='monsterRanch2Panel';panel.className='forge-card';const options=parentOptions(),incubator=state.ranchFacilityLevel('incubator');panel.innerHTML=`<div class="forge-card-top"><div class="forge-card-name">Monster Ranch 2.0 — 牧場施設</div><strong>牧舎Lv.${state.settlementLevel?.('ranch')||0}</strong></div><div class="forge-card-sub">牧舎の中に専門施設を建て、育成・配合・変異研究を拡張する。</div>${facilityCards()}<div class="forge-card" style="margin-top:8px"><div class="forge-card-name">🥚 孵化場</div>${eggCards()}</div><div class="forge-card" style="margin-top:8px"><div class="forge-card-name">🧬 配合卵</div><div class="forge-card-sub">従来の即時配合は残しつつ、孵化場Lv.1から2.0方式の「配合卵」を作れる。</div>${incubator<1?'<div class="forge-card-sub">孵化場Lv.1で解放</div>':`<label class="forge-card-sub">親A<select id="ranch2ParentA" style="width:100%">${options}</select></label><label class="forge-card-sub">親B<select id="ranch2ParentB" style="width:100%">${options}</select></label><button id="ranch2BreedEgg" class="btn-highlight">配合卵を作る</button><div id="ranch2Msg" class="forge-card-sub"></div>`}</div>`;root.prepend(panel);panel.querySelectorAll('.ranch2-upgrade').forEach(b=>b.addEventListener('click',()=>{state.upgradeRanchFacility(b.dataset.id);installRanch2Panel();}));panel.querySelectorAll('.ranch2-hatch').forEach(b=>b.addEventListener('click',()=>{const r=state.hatchRanchEgg(b.dataset.id);if(!r.ok){window.alert(r.reason==='full'?'牧場が満員です。':'孵化できません。');return;}installRanch2Panel();}));const breed=panel.querySelector('#ranch2BreedEgg');if(breed){const a=panel.querySelector('#ranch2ParentA'),b=panel.querySelector('#ranch2ParentB'),msg=panel.querySelector('#ranch2Msg');if(b.options.length>1)b.selectedIndex=1;breed.addEventListener('click',()=>{const r=state.createBreedingEgg(a.value,b.value);msg.textContent=r.ok?'🥚 配合卵が生まれた！':r.reason==='cost'?'Goldまたは魔石が足りません。':r.reason==='parents'?'異なる2体を選んでください。':'配合卵を作れません。';installRanch2Panel();});}}
// installRanch2Panel() removes+recreates #monsterRanch2Panel every call, which
// is itself a childList mutation on the observed root — calling it directly
// from the observer would retrigger the observer forever and hang the tab
// before the page even finishes loading. The observer only needs to reinsert
// the panel after something else (e.g. renderMonsterRanch()'s innerHTML
// replace) wipes it out, so it must no-op once the panel is already present.
function ensureInserted(){if(!document.getElementById('monsterRanch2Panel'))installRanch2Panel();}
function watch(){const root=document.getElementById('companionContent');if(!root)return;new MutationObserver(()=>queueMicrotask(ensureInserted)).observe(root,{childList:true});queueMicrotask(installRanch2Panel);}if(typeof MutationObserver!=='undefined')watch();
