/* Monster Ranch 2.0 — advanced facility UI */
import { state } from '../state.js';
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');}
function companions(){return state.companionList?.()||[];}
function optionList(){return companions().map(c=>`<option value="${esc(c.id)}">${esc(c.instance.nickname||c.species.name)} Lv.${c.instance.level}</option>`).join('');}
function render(){const root=document.getElementById('companionContent');if(!root||!state.ranchResearchUnlocks)return;document.getElementById('ranch2Advanced')?.remove();const p=document.createElement('div');p.id='ranch2Advanced';p.className='forge-card';const opts=optionList(),unlocks=state.ranchResearchUnlocks(),runs=state.ranchExpeditionList?.()||[];p.innerHTML=`<div class="forge-card-name">Monster Ranch 2.0 — 育成・研究・派遣</div><div class="forge-card" style="margin-top:8px"><strong>訓練場</strong><div class="forge-card-sub">個体を指定してEXP・Bondを獲得。専門訓練は対象能力を最大+10%まで鍛える。</div>${state.ranchFacilityLevel('training')<1?'Lv.1で解放':`<select id="r2train">${opts}</select><select id="r2focus"><option value="balanced">総合</option><option value="power">ATK</option><option value="guard">DEF</option><option value="magic">MAG</option><option value="speed">SPD</option></select><button id="r2trainBtn" class="btn-highlight">訓練する</button>`}</div><div class="forge-card" style="margin-top:8px"><strong>魔物研究所</strong><div class="forge-card-sub">Lv1 野生卵 / Lv2 Trait解析 / Lv3 指定継承 / Lv4 変異系譜 / Lv5 MASTER Archive</div><div class="forge-card-sub">現在: ${Object.entries(unlocks).filter(([,v])=>v).map(([k])=>k).join(' / ')||'未解放'}</div></div><div class="forge-card" style="margin-top:8px"><strong>派遣</strong><div class="forge-card-sub">最大3体を派遣。素材・EXP・Bond・希少卵を持ち帰る。</div>${Object.values(state.ranchExpeditionDefs||{}).map(d=>`<button class="btn-sub r2exp" data-id="${d.id}" ${state.ranchFacilityLevel('research')<d.minLv?'disabled':''}>${esc(d.name)}（研究Lv.${d.minLv}）</button>`).join('')}<select id="r2expComp">${opts}</select>${runs.map(r=>`<div class="forge-card-sub">${esc(r.def?.name)} — ${r.ready?'帰還済み':'派遣中'} ${r.ready?`<button class="btn-highlight r2claim" data-id="${r.id}">報酬受取</button>`:''}</div>`).join('')}</div>`;root.appendChild(p);p.querySelector('#r2trainBtn')?.addEventListener('click',()=>{state.trainRanchCompanion(p.querySelector('#r2train').value,p.querySelector('#r2focus').value);render();});p.querySelectorAll('.r2exp').forEach(b=>b.addEventListener('click',()=>{state.startRanchExpedition([p.querySelector('#r2expComp').value],b.dataset.id);render();}));p.querySelectorAll('.r2claim').forEach(b=>b.addEventListener('click',()=>{state.claimRanchExpedition(b.dataset.id);render();}));}
// render() removes+recreates #ranch2Advanced every call, which is itself a
// childList mutation on the observed root — calling render() directly from
// the observer would retrigger the observer forever and hang the tab before
// the page even finishes loading. The observer only needs to reinsert the
// panel after something else (e.g. renderMonsterRanch()'s innerHTML replace)
// wipes it out, so it must no-op once the panel is already present.
function ensureInserted(){if(!document.getElementById('ranch2Advanced'))render();}
if(typeof MutationObserver!=='undefined'){const root=document.getElementById('companionContent');if(root)new MutationObserver(()=>queueMicrotask(ensureInserted)).observe(root,{childList:true});}queueMicrotask(render);
