import { state } from '../state.js';
import { RESEARCH_UNLOCK_HALL_LEVEL } from '../data/settlementResearch.js';

function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id)?.classList.add('active');}
function detailText(domain){const d=domain.details||{};if(domain.id==='taxonomy')return `役割判明 ${d.roleKnown||0} / 行動判明 ${d.behaviorKnown||0}${d.skills?.length?` / 観測技 ${d.skills.slice(0,6).join('・')}${d.skills.length>6?'…':''}`:''}`;if(domain.id==='affinity'){const parts=[];for(const [element,tiers] of Object.entries(d.affinities||{}))parts.push(`${element}: ${Object.entries(tiers).map(([tier,n])=>`${tier}×${n}`).join(', ')}`);return parts.join(' / ')||'属性相性の観測記録なし';}if(domain.id==='elite')return d.observed?.length?d.observed.join(' / '):'Elite Affix観測なし';if(domain.id==='rare')return d.observed?.length?d.observed.join(' / '):'Rare Behavior観測なし';if(domain.id==='boss')return `Boss Phase観測・解析 ${d.observed||0}件`;return '観測記録なし';}
function renderResearch(){const content=document.getElementById('settlementResearchContent');if(!content)return;if(!state.settlementResearchUnlocked?.()){content.innerHTML=`<div class="forge-card" data-settlement-research><div class="forge-card-top"><div class="forge-card-name">🔬 研究所・Codex Lab</div><strong>LOCKED</strong></div><div class="forge-card-sub">交易町（集会所Lv.${RESEARCH_UNLOCK_HALL_LEVEL}）で解禁。未遭遇情報は研究所だけでは開示されない。</div></div>`;return;}const report=state.settlementResearchReport?.()||{seenCount:0,analyzedCount:0},domains=state.settlementResearchDomains?.()||[],outlook=state.settlementResearchOutlook?.()||[];const domainHtml=domains.map(d=>`<div class="forge-card" data-research-domain="${d.id}" style="padding:10px 12px;"><div class="forge-card-top"><div class="forge-card-name">${d.icon} ${d.name}</div><strong>Lv.${d.tier} ${d.tierName}</strong></div><div class="forge-card-sub">${d.desc}</div><div class="forge-card-sub" style="margin-top:6px;">証拠 ${d.evidence}件 ／ ${detailText(d)}</div><button class="forge-card-btn research-review" data-domain="${d.id}" ${d.tier>0&&d.reviewedTier<d.tier?'':'disabled'} style="margin-top:8px;">${d.tier<=0?'観測待ち':d.reviewedTier>=d.tier?'整理済み':'研究記録を整理'}</button></div>`).join('');const outlookHtml=outlook.length?outlook.map(x=>`<div class="forge-card" data-research-outlook="${x.id}" style="padding:10px 12px;"><div class="forge-card-top"><div class="forge-card-name">${x.icon} ${x.title}</div><strong>${x.source}</strong></div><div class="forge-card-sub">${x.text}</div></div>`).join(''):'<div class="forge-card"><div class="forge-card-sub">現在、観測済みデータから追加予測できる情報はない。未発見領域の名称やBoss情報を研究所が先回りして開示することはない。</div></div>';content.innerHTML=`<div class="forge-card" data-settlement-research><div class="forge-card-top"><div class="forge-card-name">🔬 研究所・Codex Lab</div><strong>交易町+</strong></div><div class="forge-card-sub">Codexで実際に観測した記録だけを横断解析する。敵データ表から未遭遇情報を逆引きせず、未遭遇情報は研究所だけでは開示されない。</div><div class="forge-card-sub" style="margin-top:8px;">観測済み ${report.seenCount}種 ／ 詳細解析済み ${report.analyzedCount}種</div></div><section style="margin-top:12px;"><div class="forge-card-name" style="margin-bottom:8px;">📑 研究分野</div><div style="display:grid;gap:8px;">${domainHtml}</div></section><section style="margin-top:12px;"><div class="forge-card-name" style="margin-bottom:8px;">🔭 観測予測・ヒント</div><div style="display:grid;gap:8px;">${outlookHtml}</div></section>`;content.querySelectorAll('.research-review').forEach(btn=>btn.addEventListener('click',()=>{const r=state.reviewSettlementResearchDomain?.(btn.dataset.domain);if(r?.ok)renderResearch();}));}
function install(){const settlement=document.getElementById('settlementScreen');if(settlement&&!document.getElementById('settlementResearchBtn')){const header=settlement.querySelector('.subbar');const btn=document.createElement('button');btn.id='settlementResearchBtn';btn.className='btn-back';btn.textContent='🔬';btn.title='研究所';header?.appendChild(btn);btn.addEventListener('click',()=>{renderResearch();showScreen('settlementResearchScreen');});}if(!document.getElementById('settlementResearchScreen')){const section=document.createElement('section');section.id='settlementResearchScreen';section.className='screen';section.innerHTML='<header class="subbar"><button class="btn-back" id="settlementResearchBackBtn">←</button><h2>研究所・Codex Lab</h2></header><div id="settlementResearchContent" class="blacksmith-content"></div>';document.body.insertBefore(section,document.querySelector('.toast'));document.getElementById('settlementResearchBackBtn')?.addEventListener('click',()=>showScreen('settlementScreen'));}}
install();
export { renderResearch };
