import { state } from '../state.js';
import { SETTLEMENT_EXPEDITIONS,settlementExpeditionEligible } from '../data/settlementExpeditions.js';
const META_KEY='__settlement3';
function ensure(){if(!state.data.settlementBuildings)state.data.settlementBuildings={hall:0,inn:0,market:0,watch:0,ranch:0};let root=state.data.settlementBuildings[META_KEY];if(!root||typeof root!=='object'||Array.isArray(root)){root={};state.data.settlementBuildings[META_KEY]=root;}let e=root.expeditions;let changed=false;if(!e||typeof e!=='object'||Array.isArray(e)){e={active:null,completed:[],discoveries:[]};root.expeditions=e;changed=true;}if(!Array.isArray(e.completed)){e.completed=[];changed=true;}if(!Array.isArray(e.discoveries)){e.discoveries=[];changed=true;}if(e.active!==null&&typeof e.active!=='object'){e.active=null;changed=true;}if(changed)state.save();return e;}
function hall(){return state.settlementLevel?.('hall')||0;}
function cycle(){return state.settlementSeasonState?.().cycle||0;}
function agentPool(){const companions=(state.settlementRanch3Roster?.()||[]).filter(x=>!x.favorite).map(x=>({id:`companion:${x.id}`,source:'companion',refId:x.id,name:x.name,detail:`Lv.${x.level} ${x.species}`}));const residents=(state.settlementResidents?.()||[]).filter(x=>x.joined).map(x=>({id:`resident:${x.id}`,source:'resident',refId:x.id,name:x.name,detail:x.roleName||x.role||'住民'}));return[...companions,...residents];}
state.settlementExpeditionAgents=function(){const active=ensure().active?.members||[],favored=this.settlementPolicyBias?.('ranch')===1;return agentPool().map(a=>({...a,away:active.includes(a.id),policyFavored:favored&&a.source==='companion'})).sort((a,b)=>favored?Number(b.source==='companion')-Number(a.source==='companion'):0);};
state.settlementExpeditionMissions=function(){const e=ensure(),c={hall:hall()};return SETTLEMENT_EXPEDITIONS.map(m=>({...m,available:settlementExpeditionEligible(m,c),active:e.active?.missionId===m.id,completed:e.completed.includes(m.id)}));};
state.settlementExpeditionState=function(){const e=ensure();return{active:e.active?{...e.active,members:[...e.active.members]}:null,completed:[...e.completed],discoveries:[...e.discoveries]};};
state.dispatchSettlementExpedition=function(missionId,members=[]){const e=ensure(),mission=SETTLEMENT_EXPEDITIONS.find(x=>x.id===missionId);if(!mission)return{ok:false,reason:'unknown'};if(e.active)return{ok:false,reason:'active'};if(!settlementExpeditionEligible(mission,{hall:hall()}))return{ok:false,reason:'locked'};const pool=new Set(agentPool().map(a=>a.id)),chosen=[...new Set(members)].filter(id=>pool.has(id)).slice(0,mission.maxMembers);if(!chosen.length)return{ok:false,reason:'members'};e.active={missionId,startCycle:cycle(),members:chosen};this.save();return{ok:true,mission,active:{...e.active}};};
state.resolveSettlementExpedition=function(){const e=ensure();if(!e.active)return{ok:false,reason:'none'};const mission=SETTLEMENT_EXPEDITIONS.find(x=>x.id===e.active.missionId);if(!mission){e.active=null;this.save();return{ok:false,reason:'unknown'};}const elapsed=Math.max(0,cycle()-Number(e.active.startCycle||0));if(elapsed<mission.cycles)return{ok:false,reason:'traveling',remaining:mission.cycles-elapsed};const first=!e.completed.includes(mission.id);if(first)e.completed.push(mission.id);if(!e.discoveries.some(x=>x.id===mission.lead.id))e.discoveries.push({...mission.lead,missionId:mission.id});const gained=this.addSettlementMaterials?.(mission.reward||{})||{};const members=[...e.active.members];if(members.some(id=>id.startsWith('companion:')))this.recordSettlementFactionActivity?.('tamers',1);e.active=null;this.save();return{ok:true,mission,members,gained,lead:mission.lead,first};};
