import { state } from '../state.js';
import { SETTLEMENT_MATERIALS,settlementCost } from '../data/settlement.js';
import { pixelIconHtml } from '../ui/pixelIcons.js';
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id)?.classList.add('active');}
const BUILDING_ICON={hall:'settlement',inn:'heal',market:'market',watch:'adventure',ranch:'ranch'};
function materialLine(){return Object.values(SETTLEMENT_MATERIALS).map(m=>`<span class="pixel-resource">${pixelIconHtml(m.id,'sm')}<span>${m.name} ${state.data.settlementMaterials?.[m.id]||0}</span></span>`).join('　');}
function costText(cost){return Object.entries(cost||{}).filter(([,v])=>v>0).map(([k,v])=>`<span class="pixel-resource">${pixelIconHtml(k,'sm')}<span>${v}</span></span>`).join(' ');}
export function renderSettlement(){const content=document.getElementById('settlementContent');if(!content)return;const hall=state.settlementLevel('hall');const top=`<div class="forge-card"><div class="forge-card-top"><div class="forge-card-name">${pixelIconHtml('settlement')} 開拓拠点</div><strong>集会所 Lv.${hall}</strong></div><div class="forge-card-sub">冒険で素材を集め、施設を育てる恒久拠点。牧舎は次のMonster Ranchへ接続する。</div><div class="forge-card-sub" style="margin-top:8px;">${materialLine()}</div></div>`;const cards=state.settlementBuildings.map(b=>{const lv=state.settlementLevel(b.id),next=Math.min(b.maxLevel,lv+1),check=state.canUpgradeSettlement(b.id),cost=lv<b.maxLevel?settlementCost(b.id,next):null;let status='';if(check.ok)status='強化可能';else if(check.reason==='hall')status=`集会所Lv.${next}が必要`;else if(check.reason==='materials')status='素材不足';else if(check.reason==='max')status='MAX';return `<div class="forge-card"><div class="forge-card-top"><div class="forge-card-name">${pixelIconHtml(BUILDING_ICON[b.id]||'settlement')} ${b.name}</div><strong>Lv.${lv}/${b.maxLevel}</strong></div><div class="forge-card-sub">${b.desc}</div><div class="forge-card-sub" style="margin-top:6px;">${lv>=b.maxLevel?'最大強化':`次Lv費用: ${costText(cost)} ／ ${status}`}</div><button class="forge-card-btn settlement-upgrade" data-building="${b.id}" ${check.ok?'':'disabled'}>${lv>=b.maxLevel?'MAX':'建築・強化する'}</button></div>`;}).join('');content.innerHTML=top+cards;content.querySelectorAll('.settlement-upgrade').forEach(btn=>btn.addEventListener('click',()=>{const r=state.upgradeSettlement(btn.dataset.building);if(r.ok)renderSettlement();}));}
function install(){const menu=document.querySelector('.home-menu');if(menu&&!document.getElementById('goSettlementBtn')){const btn=document.createElement('button');btn.id='goSettlementBtn';btn.className='menu-card';btn.innerHTML='<span class="menu-icon">🏘️</span><span>開拓拠点</span>';menu.appendChild(btn);btn.addEventListener('click',()=>{renderSettlement();showScreen('settlementScreen');});}if(!document.getElementById('settlementScreen')){const section=document.createElement('section');section.id='settlementScreen';section.className='screen';section.innerHTML='<header class="subbar"><button class="btn-back" id="settlementBackBtn">←</button><h2>開拓拠点</h2></header><div id="settlementContent" class="blacksmith-content"></div>';document.body.insertBefore(section,document.querySelector('.toast'));document.getElementById('settlementBackBtn').addEventListener('click',()=>showScreen('homeScreen'));}}
install();
