import { state } from '../state.js';
import { PRODUCTION_GOODS,PRODUCTION_UNLOCK_HALL_LEVEL } from '../data/settlementProduction.js';

function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id)?.classList.add('active');}
function materialText(cost={}){return Object.entries(cost).filter(([,v])=>v>0).map(([k,v])=>`${k}:${v}`).join(' / ');}
function goodsLine(){return (state.settlementProductionGoods?.()||[]).map(g=>`${g.name} ${g.amount}`).join('　');}
function renderProduction(){const content=document.getElementById('settlementProductionContent');if(!content)return;const unlocked=state.settlementProductionUnlocked?.();if(!unlocked){content.innerHTML=`<div class="forge-card"><div class="forge-card-top"><div class="forge-card-name">生産区</div><strong>LOCKED</strong></div><div class="forge-card-sub">交易町（集会所Lv.${PRODUCTION_UNLOCK_HALL_LEVEL}）で解禁。時間経過だけで資源が増える放置収入は発生しない。</div></div>`;return;}const facilities=state.settlementProductionFacilities?.()||[],recipes=state.settlementProductionRecipes?.()||[];const facilityHtml=facilities.map(f=>`<div class="forge-card" data-production-facility="${f.id}" style="padding:10px 12px;"><div class="forge-card-top"><div class="forge-card-name">${f.name}</div><strong>${f.unlocked?'稼働':'準備中'}</strong></div><div class="forge-card-sub">${f.desc}</div></div>`).join('');const recipeHtml=recipes.map(r=>{const good=PRODUCTION_GOODS[r.output.good],status=r.unlocked?(r.craftable?'加工可能':'素材不足'):'未解禁';return `<div class="forge-card" data-production-recipe="${r.id}" style="padding:10px 12px;"><div class="forge-card-top"><div class="forge-card-name">${r.name}</div><strong>${status}</strong></div><div class="forge-card-sub">材料：${materialText(r.cost)} → ${good?.name||r.output.good} ×${r.output.amount}</div><div class="forge-card-sub" style="margin-top:5px;">加工回数 ${r.crafted}</div><button class="forge-card-btn production-craft" data-recipe="${r.id}" ${r.craftable?'':'disabled'} style="margin-top:8px;">加工する</button></div>`;}).join('');content.innerHTML=`<div class="forge-card"><div class="forge-card-top"><div class="forge-card-name">生産区</div><strong>交易町+</strong></div><div class="forge-card-sub">農園・採掘場・伐採場・加工工房で、冒険から持ち帰った既存素材を加工品へ変える。自動収入・毎日回収・新通貨は追加しない。</div><div class="forge-card-sub" style="margin-top:8px;">${goodsLine()||'加工品なし'}</div></div><section style="margin-top:12px;"><div class="forge-card-name" style="margin-bottom:8px;">生産施設</div><div style="display:grid;gap:8px;">${facilityHtml}</div></section><section style="margin-top:12px;"><div class="forge-card-name" style="margin-bottom:8px;">加工レシピ</div><div style="display:grid;gap:8px;">${recipeHtml}</div></section>`;content.querySelectorAll('.production-craft').forEach(btn=>btn.addEventListener('click',()=>{const r=state.craftSettlementProduction?.(btn.dataset.recipe);if(r?.ok)renderProduction();}));}
function install(){const settlement=document.getElementById('settlementScreen');if(settlement&&!document.getElementById('settlementProductionBtn')){const header=settlement.querySelector('.subbar');const btn=document.createElement('button');btn.id='settlementProductionBtn';btn.className='btn-back';btn.textContent='生産';btn.title='生産区';header?.appendChild(btn);btn.addEventListener('click',()=>{renderProduction();showScreen('settlementProductionScreen');});}if(!document.getElementById('settlementProductionScreen')){const section=document.createElement('section');section.id='settlementProductionScreen';section.className='screen';section.innerHTML='<header class="subbar"><button class="btn-back" id="settlementProductionBackBtn">←</button><h2>生産区</h2></header><div id="settlementProductionContent" class="blacksmith-content"></div>';document.body.insertBefore(section,document.querySelector('.toast'));document.getElementById('settlementProductionBackBtn')?.addEventListener('click',()=>showScreen('settlementScreen'));}}
install();
export { renderProduction };
