import { state } from '../state.js';
import { PRODUCTION_FACILITIES,PRODUCTION_GOODS,PRODUCTION_RECIPES,PRODUCTION_UNLOCK_HALL_LEVEL,productionCanCraft,productionFacilityUnlocked,productionRecipeUnlocked } from '../data/settlementProduction.js';

const META_KEY='__settlement3';
function productionMeta(){const root=state.data.settlementBuildings??={hall:0,inn:0,market:0,watch:0,ranch:0};const meta=root[META_KEY]??={};if(!meta.production||typeof meta.production!=='object')meta.production={goods:{},crafted:{}};if(!meta.production.goods||typeof meta.production.goods!=='object')meta.production.goods={};if(!meta.production.crafted||typeof meta.production.crafted!=='object')meta.production.crafted={};for(const id of Object.keys(PRODUCTION_GOODS))if(!Number.isFinite(meta.production.goods[id]))meta.production.goods[id]=0;root[META_KEY]=meta;return meta.production;}
function context(){return{hall:state.settlementLevel?.('hall')||0,buildings:state.data.settlementBuildings||{},materials:state.data.settlementMaterials||{}};}
state.settlementProductionUnlocked=function(){return (this.settlementLevel?.('hall')||0)>=PRODUCTION_UNLOCK_HALL_LEVEL;};
state.settlementProductionGoods=function(){const p=productionMeta();return Object.values(PRODUCTION_GOODS).map(g=>({...g,amount:Math.max(0,Math.floor(p.goods[g.id]||0))}));};
state.settlementProductionFacilities=function(){const c=context();return PRODUCTION_FACILITIES.map(f=>({...f,unlocked:productionFacilityUnlocked(f,c)}));};
state.settlementProductionRecipes=function(){const c=context(),p=productionMeta();return PRODUCTION_RECIPES.map(r=>({...r,unlocked:productionRecipeUnlocked(r,c),craftable:productionCanCraft(r,c),crafted:Math.max(0,Math.floor(p.crafted[r.id]||0))}));};
state.craftSettlementProduction=function(id){const recipe=PRODUCTION_RECIPES.find(x=>x.id===id);if(!recipe)return{ok:false,reason:'unknown'};const c=context();if(!productionRecipeUnlocked(recipe,c))return{ok:false,reason:'locked'};if(!productionCanCraft(recipe,c))return{ok:false,reason:'materials'};for(const [key,value] of Object.entries(recipe.cost||{}))this.data.settlementMaterials[key]=Math.max(0,(Number(this.data.settlementMaterials[key])||0)-value);const p=productionMeta(),good=recipe.output.good,amount=Math.max(1,Math.floor(recipe.output.amount||1));p.goods[good]=(p.goods[good]||0)+amount;p.crafted[id]=(p.crafted[id]||0)+1;this.save();return{ok:true,good,amount};};
