import { state } from '../state.js';
import { BLACK_MARKET,MARKET2_UNLOCK_HALL_LEVEL,MARKET_OFFERS,TRADE_ROUTES,marketCanPay,marketOfferAvailable,tradeRequirementMet,tradeRouteDiscovered } from '../data/settlementMarket.js';

const META_KEY='__settlement3';
function marketMeta(){const root=state.data.settlementBuildings??={hall:0,inn:0,market:0,watch:0,ranch:0};const meta=root[META_KEY]??={};if(!meta.market2||typeof meta.market2!=='object')meta.market2={securedRoutes:[],purchases:{}};if(!Array.isArray(meta.market2.securedRoutes))meta.market2.securedRoutes=[];if(!meta.market2.purchases||typeof meta.market2.purchases!=='object')meta.market2.purchases={};root[META_KEY]=meta;return meta.market2;}
function codex(){return Object.values(state.data.monsterCodex||{});}
function stageClears(){return Object.values(state.data.stageProgress||{}).filter(v=>v===true||v?.cleared||Number(v)>0).length;}
function goodsMap(){return Object.fromEntries((state.settlementProductionGoods?.()||[]).map(g=>[g.id,g.amount]));}
function context(){const entries=codex(),m=marketMeta();return{hall:state.settlementLevel?.('hall')||0,stageClears:stageClears(),codexKills:entries.reduce((n,e)=>n+(Number(e?.kills)||0),0),recruitedCodex:entries.filter(e=>e?.recruited).length,rareSeen:entries.filter(e=>e?.rare||e?.legendary).length,abyssBestDepth:Math.max(0,Number(state.data.abyssBestDepth)||0),securedRoutes:[...m.securedRoutes],gold:Number(state.data.gold)||0,materials:state.data.settlementMaterials||{},goods:goodsMap()};}
function productionMeta(){const root=state.data.settlementBuildings?.[META_KEY];return root?.production||null;}
function spend(cost={}){if(cost.gold)state.data.gold=Math.max(0,(Number(state.data.gold)||0)-cost.gold);for(const [k,v] of Object.entries(cost.materials||{}))state.data.settlementMaterials[k]=Math.max(0,(Number(state.data.settlementMaterials?.[k])||0)-v);const p=productionMeta();for(const [k,v] of Object.entries(cost.goods||{}))if(p?.goods)p.goods[k]=Math.max(0,(Number(p.goods[k])||0)-v);}
function grant(reward={}){state.data.settlementMaterials??={wood:0,ore:0,hide:0,veilstone:0};for(const [k,v] of Object.entries(reward.materials||{}))if(k in state.data.settlementMaterials)state.data.settlementMaterials[k]=(Number(state.data.settlementMaterials[k])||0)+Math.max(0,Math.floor(v));if(reward.gold)state.data.gold=(Number(state.data.gold)||0)+Math.max(0,Math.floor(reward.gold));}
state.settlementMarket2Unlocked=function(){return (this.settlementLevel?.('hall')||0)>=MARKET2_UNLOCK_HALL_LEVEL;};
state.settlementTradeRoutes=function(){const c=context();return TRADE_ROUTES.map(route=>({...route,discovered:tradeRouteDiscovered(route,c),secured:c.securedRoutes.includes(route.id),canSecure:tradeRouteDiscovered(route,c)&&!c.securedRoutes.includes(route.id)&&marketCanPay({materials:route.secureCost},{...c,gold:Infinity})}));};
state.secureSettlementTradeRoute=function(id){const route=TRADE_ROUTES.find(x=>x.id===id);if(!route)return{ok:false,reason:'unknown'};const c=context(),m=marketMeta();if(!tradeRouteDiscovered(route,c))return{ok:false,reason:'undiscovered'};if(m.securedRoutes.includes(id))return{ok:false,reason:'secured'};if(!marketCanPay({materials:route.secureCost},{...c,gold:Infinity}))return{ok:false,reason:'materials'};spend({materials:route.secureCost});m.securedRoutes.push(id);this.save();return{ok:true,route};};
state.settlementMarketOffers=function(){const c=context(),m=marketMeta(),favored=this.settlementPolicyBias?.('market')===1;return MARKET_OFFERS.map(offer=>{const bought=Math.max(0,Math.floor(m.purchases[offer.id]||0)),available=marketOfferAvailable(offer,c)&&bought<offer.stock;return{...offer,bought,remaining:Math.max(0,offer.stock-bought),unlocked:marketOfferAvailable(offer,c),affordable:available&&marketCanPay(offer.cost,c),policyFavored:favored};}).sort((a,b)=>favored?Number(b.affordable)-Number(a.affordable)||Number(b.unlocked)-Number(a.unlocked):0);};
state.buySettlementMarketOffer=function(id){const offer=MARKET_OFFERS.find(x=>x.id===id);if(!offer)return{ok:false,reason:'unknown'};const c=context(),m=marketMeta(),bought=Math.max(0,Math.floor(m.purchases[id]||0));if(!marketOfferAvailable(offer,c))return{ok:false,reason:'route'};if(bought>=offer.stock)return{ok:false,reason:'stock'};if(!marketCanPay(offer.cost,c))return{ok:false,reason:'cost'};spend(offer.cost);grant(offer.reward);m.purchases[id]=bought+1;this.recordSettlementFactionActivity?.('guild',1);this.save();return{ok:true,offer};};
state.settlementBlackMarket=function(){const c=context();return{...BLACK_MARKET,discovered:tradeRequirementMet(BLACK_MARKET.discover,c)};};
