/* World 2.0 — regional progression, keys, realms, random events */
import { state } from '../state.js';
import { CHAPTERS } from '../data/stages.js';
import { TextBattleScreen } from '../screens/textBattle.js';
import { KEY_DUNGEON_TYPES,availableKeyDungeons,realmVisibility,rollWorldEvent,worldProgressFromClears } from '../data/world2.js';
function ensure(){let changed=false;if(!state.data.world2){state.data.world2={keyFragments:0,keys:{},eventsSeen:{},flags:{},lastEvent:null};changed=true;}state.data.world2.keys||={};state.data.world2.eventsSeen||={};state.data.world2.flags||={};if(!Number.isFinite(state.data.world2.keyFragments))state.data.world2.keyFragments=0;if(changed)state.save();}
ensure();
state.world2Progress=function(){return worldProgressFromClears(CHAPTERS,id=>this.isStageCleared(id));};
state.world2RealmVisibility=function(){ensure();return realmVisibility(this.world2Progress(),this.data.world2.flags);};
state.world2KeyFragments=function(){ensure();return Math.max(0,Math.floor(this.data.world2.keyFragments||0));};
state.world2AvailableKeyDungeons=function(){ensure();return availableKeyDungeons(this.world2Progress(),this.world2KeyFragments());};
state.world2ForgeKey=function(typeId){ensure();const def=KEY_DUNGEON_TYPES[typeId];if(!def)return{ok:false,reason:'unknown'};if(this.world2Progress()<def.minProgress)return{ok:false,reason:'progress',required:def.minProgress};if(this.world2KeyFragments()<def.fragmentCost)return{ok:false,reason:'fragments',cost:def.fragmentCost};this.data.world2.keyFragments-=def.fragmentCost;this.data.world2.keys[typeId]=(this.data.world2.keys[typeId]||0)+1;this.save();return{ok:true,typeId,count:this.data.world2.keys[typeId]};};
state.world2UseKey=function(typeId){ensure();const def=KEY_DUNGEON_TYPES[typeId],count=this.data.world2.keys[typeId]||0;if(!def||count<=0)return{ok:false,reason:'missing'};this.data.world2.keys[typeId]--;if(typeId==='celestial')this.data.world2.flags.heavenOpened=true;if(typeId==='infernal')this.data.world2.flags.underworldOpened=true;if(typeId==='anomaly')this.data.world2.flags.modernContact=true;this.save();return{ok:true,dungeon:{...def,seed:Date.now(),depth:1}};};
state.world2ResolveEvent=function(eventId,choiceIndex=0){ensure();const event=this.data.world2.lastEvent;if(!event||event.id!==eventId)return{ok:false,reason:'missing'};const choice=event.choices?.[choiceIndex]||event.choices?.[0];const result={gold:0,keyFragments:0,choice};if(event.id==='traveler'&&choiceIndex===0){result.gold=150+this.world2Progress()*25;this.data.gold=(this.data.gold||0)+result.gold;}else if(event.id==='shrine'){result.keyFragments=1;this.data.world2.keyFragments++;}else if(event.id==='tracks'&&choiceIndex===0){result.keyFragments=1;this.data.world2.keyFragments++;}else if(event.id==='rift'||event.id==='keyhole'){result.keyFragments=1;this.data.world2.keyFragments++;}this.data.world2.eventsSeen[event.id]=(this.data.world2.eventsSeen[event.id]||0)+1;this.data.world2.lastEvent=null;this.save();return{ok:true,result};};
state.rollWorld2ClearRewards=function(stage,{rng=Math.random}={}){ensure();const progress=this.world2Progress();let fragment=0;if(progress>=5&&rng()<Math.min(.12,.025+progress*.003)){this.data.world2.keyFragments++;fragment=1;}let event=null;if(rng()<.14){event=rollWorldEvent(rng);this.data.world2.lastEvent={...event,stageId:stage?.id||null};}if(fragment||event)this.save();return{fragment,event};};
const previousStart=TextBattleScreen.prototype.start;TextBattleScreen.prototype.start=function(stageId,onEnd,blessingId){return previousStart.call(this,stageId,result=>{if(result?.cleared&&!result.retreated){result.world2=state.rollWorld2ClearRewards?.(this.engine?.stage||{id:stageId})||null;}onEnd(result);},blessingId);};
